#include <trx/config/enum.h>
#include <trx/core/enum_map.h>
#include <trx/game/game_buf.h>
#include <trx/game/game_flow/types.h>
#include <trx/game/gun/types.h>
#include <trx/game/input/enum.h>
#include <trx/game/lara/skin/types.h>
#include <trx/game/lara/types.h>
#include <trx/game/objects/ids.h>
#include <trx/game/screenshot.h>
#include <trx/game/ui/settings.h>

static __attribute__((constructor)) void M_Init(void)
{
#define X_INPUT_ROLE(role_name, state_name)                                    \
    ENUM_MAP(INPUT_ROLE, role_name, #state_name);
#include <trx/game/input/roles.def>
#undef X_INPUT_ROLE

    ENUM_MAP(GAME_BUFFER, GBUF_TEXTURE_PAGES, "Texture pages");
    ENUM_MAP(GAME_BUFFER, GBUF_PALETTES, "Color palettes");
    ENUM_MAP(GAME_BUFFER, GBUF_OBJECT_TEXTURES, "Object textures");
    ENUM_MAP(GAME_BUFFER, GBUF_SPRITE_TEXTURES, "Sprite textures");
    ENUM_MAP(GAME_BUFFER, GBUF_STATIC_OBJECTS_3D, "Static objects (3D)");
    ENUM_MAP(GAME_BUFFER, GBUF_STATIC_OBJECTS_2D, "Static objects (2D)");
    ENUM_MAP(GAME_BUFFER, GBUF_MESH_POINTERS, "Mesh pointers");
    ENUM_MAP(GAME_BUFFER, GBUF_MESHES, "Meshes");
    ENUM_MAP(GAME_BUFFER, GBUF_ANIMS, "Animations");
    ENUM_MAP(GAME_BUFFER, GBUF_ANIM_CHANGES, "Animation changes");
    ENUM_MAP(GAME_BUFFER, GBUF_ANIM_RANGES, "Animation ranges");
    ENUM_MAP(GAME_BUFFER, GBUF_ANIM_COMMANDS, "Animation commands");
    ENUM_MAP(GAME_BUFFER, GBUF_ANIM_BONES, "Animation bones");
    ENUM_MAP(GAME_BUFFER, GBUF_ANIM_FRAMES, "Animation frames");
    ENUM_MAP(GAME_BUFFER, GBUF_ROOMS, "Rooms");
    ENUM_MAP(GAME_BUFFER, GBUF_ROOM_MESH, "Room meshes");
    ENUM_MAP(GAME_BUFFER, GBUF_ROOM_PORTALS, "Room portals");
    ENUM_MAP(GAME_BUFFER, GBUF_ROOM_SECTORS, "Room sectors");
    ENUM_MAP(GAME_BUFFER, GBUF_ROOM_LIGHTS, "Room lights");
    ENUM_MAP(GAME_BUFFER, GBUF_ROOM_STATIC_MESHES, "Room static meshes");
    ENUM_MAP(GAME_BUFFER, GBUF_FLOOR_DATA, "Floor data");
    ENUM_MAP(GAME_BUFFER, GBUF_ITEMS, "Items");
    ENUM_MAP(GAME_BUFFER, GBUF_ITEM_DATA, "Item data");
    ENUM_MAP(GAME_BUFFER, GBUF_EFFECTS, "Effects");
    ENUM_MAP(GAME_BUFFER, GBUF_CAMERAS, "Cameras");
    ENUM_MAP(GAME_BUFFER, GBUF_SOUND_SOURCES, "Sound sources");
    ENUM_MAP(GAME_BUFFER, GBUF_BOXES, "Boxes");
    ENUM_MAP(GAME_BUFFER, GBUF_OVERLAPS, "Overlaps");
    ENUM_MAP(GAME_BUFFER, GBUF_GROUND_ZONE, "Ground zones");
    ENUM_MAP(GAME_BUFFER, GBUF_FLY_ZONE, "Fly zones");
    ENUM_MAP(
        GAME_BUFFER, GBUF_ANIMATED_TEXTURE_RANGES, "Animated texture ranges");
    ENUM_MAP(GAME_BUFFER, GBUF_CINEMATIC_FRAMES, "Cinematic frames");
    ENUM_MAP(GAME_BUFFER, GBUF_DEMO_BUFFER, "Demo buffer");
    ENUM_MAP(GAME_BUFFER, GBUF_CREATURE_DATA, "Creature data");
    ENUM_MAP(GAME_BUFFER, GBUF_CREATURE_LOT, "Creature pathfinding");
    ENUM_MAP(GAME_BUFFER, GBUF_SAMPLE_INFOS, "Sample information");
    ENUM_MAP(GAME_BUFFER, GBUF_SAMPLES, "Samples");
    ENUM_MAP(GAME_BUFFER, GBUF_WALKABLES, "Walkables buffer");

    ENUM_MAP(GF_SEQUENCE_EVENT_TYPE, GFS_LOOP_GAME, "loop_game");
    ENUM_MAP(GF_SEQUENCE_EVENT_TYPE, GFS_PLAY_FMV, "play_fmv");
    ENUM_MAP(GF_SEQUENCE_EVENT_TYPE, GFS_PLAY_CUTSCENE, "play_cutscene");
    ENUM_MAP(GF_SEQUENCE_EVENT_TYPE, GFS_PLAY_MUSIC, "play_music");
    ENUM_MAP(GF_SEQUENCE_EVENT_TYPE, GFS_LOADING_SCREEN, "loading_screen");
    ENUM_MAP(GF_SEQUENCE_EVENT_TYPE, GFS_DISPLAY_PICTURE, "display_picture");
    ENUM_MAP(GF_SEQUENCE_EVENT_TYPE, GFS_LEVEL_STATS, "level_stats");
    ENUM_MAP(GF_SEQUENCE_EVENT_TYPE, GFS_TOTAL_STATS, "total_stats");
    ENUM_MAP(GF_SEQUENCE_EVENT_TYPE, GFS_GLOBE_SELECT, "globe_select");
    ENUM_MAP(GF_SEQUENCE_EVENT_TYPE, GFS_EXIT_TO_TITLE, "exit_to_title");
    ENUM_MAP(GF_SEQUENCE_EVENT_TYPE, GFS_LEVEL_COMPLETE, "level_complete");
    ENUM_MAP(GF_SEQUENCE_EVENT_TYPE, GFS_ADD_ITEM, "give_item");
    ENUM_MAP(GF_SEQUENCE_EVENT_TYPE, GFS_REMOVE_WEAPONS, "remove_weapons");
    ENUM_MAP(GF_SEQUENCE_EVENT_TYPE, GFS_REMOVE_AMMO, "remove_ammo");
    ENUM_MAP(GF_SEQUENCE_EVENT_TYPE, GFS_REMOVE_MEDIPACKS, "remove_medipacks");
    ENUM_MAP(GF_SEQUENCE_EVENT_TYPE, GFS_REMOVE_FLARES, "remove_flares");
    ENUM_MAP(GF_SEQUENCE_EVENT_TYPE, GFS_DISABLE_FLOOR, "disable_floor");
    ENUM_MAP(GF_SEQUENCE_EVENT_TYPE, GFS_SETUP_BACON_LARA, "setup_bacon_lara");
    ENUM_MAP(GF_SEQUENCE_EVENT_TYPE, GFS_REMOVE_SCIONS, "remove_scions");
    ENUM_MAP(
        GF_SEQUENCE_EVENT_TYPE, GFS_REMOVE_BINOCULARS, "remove_binoculars");
    ENUM_MAP(GF_SEQUENCE_EVENT_TYPE, GFS_ENABLE_SUNSET, "enable_sunset");
    ENUM_MAP(GF_SEQUENCE_EVENT_TYPE, GFS_SETUP_HORIZON, "setup_horizon");
    ENUM_MAP(GF_SEQUENCE_EVENT_TYPE, GFS_SETUP_UV_ROTATE, "setup_uv_rotate");
    ENUM_MAP(GF_SEQUENCE_EVENT_TYPE, GFS_ENABLE_LIGHTNING, "enable_lightning");
    ENUM_MAP(GF_SEQUENCE_EVENT_TYPE, GFS_SETUP_LENS_FLARE, "setup_lens_flare");
    ENUM_MAP(GF_SEQUENCE_EVENT_TYPE, GFS_SET_START_ANIM, "set_lara_start_anim");
    ENUM_MAP(
        GF_SEQUENCE_EVENT_TYPE, GFS_ADD_SECRET_REWARD, "add_secret_reward");

    ENUM_MAP(GF_LEVEL_TYPE, GFL_TITLE, "title");
    ENUM_MAP(GF_LEVEL_TYPE, GFL_NORMAL, "normal");
    ENUM_MAP(GF_LEVEL_TYPE, GFL_CUTSCENE, "cutscene");
    ENUM_MAP(GF_LEVEL_TYPE, GFL_GYM, "gym");
    ENUM_MAP(GF_LEVEL_TYPE, GFL_BONUS, "bonus");
    ENUM_MAP(GF_LEVEL_TYPE, GFL_DUMMY, "dummy");
    ENUM_MAP(GF_LEVEL_TYPE, GFL_CURRENT, "current");

    ENUM_MAP(WEATHER_TYPE, WEATHER_NONE, "none");
    ENUM_MAP(WEATHER_TYPE, WEATHER_RAIN, "rain");
    ENUM_MAP(WEATHER_TYPE, WEATHER_SNOW, "snow");

    ENUM_MAP(GF_DEATH_TILE, GF_DEATH_TILE_LAVA, "lava");
    ENUM_MAP(GF_DEATH_TILE, GF_DEATH_TILE_RAPIDS, "rapids");
    ENUM_MAP(GF_DEATH_TILE, GF_DEATH_TILE_ELECTRIC, "electric");

    ENUM_MAP_SELF(LARA_GUN_TYPE, LGT_UNARMED);
    ENUM_MAP_SELF(LARA_GUN_TYPE, LGT_PISTOLS);
    ENUM_MAP_SELF(LARA_GUN_TYPE, LGT_MAGNUMS);
    ENUM_MAP_SELF(LARA_GUN_TYPE, LGT_UZIS);
    ENUM_MAP_SELF(LARA_GUN_TYPE, LGT_SHOTGUN);
    ENUM_MAP_SELF(LARA_GUN_TYPE, LGT_M16);
    ENUM_MAP_SELF(LARA_GUN_TYPE, LGT_MP5);
    ENUM_MAP_SELF(LARA_GUN_TYPE, LGT_GRENADE);
    ENUM_MAP_SELF(LARA_GUN_TYPE, LGT_HARPOON);
    ENUM_MAP_SELF(LARA_GUN_TYPE, LGT_FLARE);
    ENUM_MAP_SELF(LARA_GUN_TYPE, LGT_SKIDOO);
    ENUM_MAP_SELF(LARA_GUN_TYPE, LGT_AUTOS);
    ENUM_MAP_SELF(LARA_GUN_TYPE, LGT_DESERT_EAGLE);
    ENUM_MAP_SELF(LARA_GUN_TYPE, LGT_ROCKET);
    ENUM_MAP_SELF(LARA_GUN_TYPE, LGT_CROSSBOW);
    ENUM_MAP_SELF(LARA_GUN_TYPE, LGT_REVOLVER);

    ENUM_MAP_SELF(WEAPON_TYPE, WEAPON_TYPE_DUAL_PISTOLS);
    ENUM_MAP_SELF(WEAPON_TYPE, WEAPON_TYPE_SINGLE_PISTOL);
    ENUM_MAP_SELF(WEAPON_TYPE, WEAPON_TYPE_RIFLE);
    ENUM_MAP_SELF(WEAPON_TYPE, WEAPON_TYPE_MOUNTED);

    ENUM_MAP(UI_BAR_TYPE, UI_BAR_LARA_HP, "lara_hp");
    ENUM_MAP(UI_BAR_TYPE, UI_BAR_LARA_HP_POISON, "lara_hp_poison");
    ENUM_MAP(UI_BAR_TYPE, UI_BAR_LARA_AIR, "lara_air");
    ENUM_MAP(UI_BAR_TYPE, UI_BAR_LARA_STAMINA, "lara_stamina");
    ENUM_MAP(UI_BAR_TYPE, UI_BAR_LARA_EXPOSURE, "lara_exposure");
    ENUM_MAP(UI_BAR_TYPE, UI_BAR_ENEMY_HP, "enemy_hp");
    ENUM_MAP(UI_BAR_TYPE, UI_BAR_ALLY_HP, "ally_hp");
    ENUM_MAP(UI_BAR_TYPE, UI_BAR_PROGRESS, "progress");

    ENUM_MAP_SELF(LARA_SKIN_BRAID_MODE, BRAID_MODE_NONE);
    ENUM_MAP_SELF(LARA_SKIN_BRAID_MODE, BRAID_MODE_TR1_HEAD_ONLY);
    ENUM_MAP_SELF(LARA_SKIN_BRAID_MODE, BRAID_MODE_TR1_FULL);
    ENUM_MAP_SELF(LARA_SKIN_BRAID_MODE, BRAID_MODE_TR1_MAULED);
    ENUM_MAP_SELF(LARA_SKIN_BRAID_MODE, BRAID_MODE_TR1_GOLD);

    ENUM_MAP_SELF(LARA_SKIN_EXTRA_MESH, EXTRA_MESH_TR1_BRAID_DEFAULT_HEAD);
    ENUM_MAP_SELF(LARA_SKIN_EXTRA_MESH, EXTRA_MESH_TR1_BRAID_COMBAT_HEAD);
    ENUM_MAP_SELF(LARA_SKIN_EXTRA_MESH, EXTRA_MESH_TR1_BRAID_DEFAULT_TORSO);
    ENUM_MAP_SELF(LARA_SKIN_EXTRA_MESH, EXTRA_MESH_TR1_BRAID_MAULED_TORSO);
    ENUM_MAP_SELF(LARA_SKIN_EXTRA_MESH, EXTRA_MESH_TR1_BRAID_GOLD_HEAD);
    ENUM_MAP_SELF(LARA_SKIN_EXTRA_MESH, EXTRA_MESH_TR1_BRAID_GOLD_TORSO);
    ENUM_MAP_SELF(LARA_SKIN_EXTRA_MESH, EXTRA_MESH_DAGGER_HAND);
    ENUM_MAP_SELF(LARA_SKIN_EXTRA_MESH, EXTRA_MESH_DAGGER_HIPS);
    ENUM_MAP_SELF(LARA_SKIN_EXTRA_MESH, EXTRA_MESH_OAR);
    ENUM_MAP_SELF(LARA_SKIN_EXTRA_MESH, EXTRA_MESH_SPANNER);
    ENUM_MAP_SELF(LARA_SKIN_EXTRA_MESH, EXTRA_MESH_DRINK_CAN);
    ENUM_MAP_SELF(LARA_SKIN_EXTRA_MESH, EXTRA_MESH_GLASSES_OPAQUE);
    ENUM_MAP_SELF(LARA_SKIN_EXTRA_MESH, EXTRA_MESH_GLASSES_TRANSPARENT);
    ENUM_MAP_SELF(LARA_SKIN_EXTRA_MESH, EXTRA_MESH_CROWBAR);

    ENUM_MAP_SELF(LARA_EXTRA_STATE, LS_EXTRA_BREATH);
    ENUM_MAP_SELF(LARA_EXTRA_STATE, LS_EXTRA_TREX_KILL);
    ENUM_MAP_SELF(LARA_EXTRA_STATE, LS_EXTRA_SCION_PICKUP_1);
    ENUM_MAP_SELF(LARA_EXTRA_STATE, LS_EXTRA_USE_MIDAS);
    ENUM_MAP_SELF(LARA_EXTRA_STATE, LS_EXTRA_MIDAS_KILL);
    ENUM_MAP_SELF(LARA_EXTRA_STATE, LS_EXTRA_SCION_PICKUP_2);
    ENUM_MAP_SELF(LARA_EXTRA_STATE, LS_EXTRA_TORSO_KILL);
    ENUM_MAP_SELF(LARA_EXTRA_STATE, LS_EXTRA_PLUNGER);
    ENUM_MAP_SELF(LARA_EXTRA_STATE, LS_EXTRA_START_ANIM);
    ENUM_MAP_SELF(LARA_EXTRA_STATE, LS_EXTRA_AIRLOCK);
    ENUM_MAP_SELF(LARA_EXTRA_STATE, LS_EXTRA_SHARK_KILL);
    ENUM_MAP_SELF(LARA_EXTRA_STATE, LS_EXTRA_YETI_KILL);
    ENUM_MAP_SELF(LARA_EXTRA_STATE, LS_EXTRA_GONG_BONG);
    ENUM_MAP_SELF(LARA_EXTRA_STATE, LS_EXTRA_GUARD_KILL);
    ENUM_MAP_SELF(LARA_EXTRA_STATE, LS_EXTRA_PULL_DAGGER);
    ENUM_MAP_SELF(LARA_EXTRA_STATE, LS_EXTRA_START_HOUSE);
    ENUM_MAP_SELF(LARA_EXTRA_STATE, LS_EXTRA_END_HOUSE);
    ENUM_MAP_SELF(LARA_EXTRA_STATE, LS_EXTRA_SHIVA_KILL);
    ENUM_MAP_SELF(LARA_EXTRA_STATE, LS_EXTRA_RAPIDS_DROWN);
    ENUM_MAP_SELF(LARA_EXTRA_STATE, LS_EXTRA_TRAIN_KILL);
    ENUM_MAP_SELF(LARA_EXTRA_STATE, LS_EXTRA_JAIL_WAKE_UP);
    ENUM_MAP_SELF(LARA_EXTRA_STATE, LS_EXTRA_WILLARD_KILL);
}
