#pragma once

#include <trx/game/ui/common.h>
#include <trx/game/ui/dialogs/color_editor.h>
#include <trx/game/ui/dialogs/controls.h>
#include <trx/game/ui/dialogs/controls_backend.h>
#include <trx/game/ui/dialogs/gameplay_settings.h>
#include <trx/game/ui/dialogs/graphic_settings.h>
#include <trx/game/ui/dialogs/new_game.h>
#include <trx/game/ui/dialogs/pause.h>
#include <trx/game/ui/dialogs/photo_mode.h>
#include <trx/game/ui/dialogs/play_any_level.h>
#include <trx/game/ui/dialogs/save_slot.h>
#include <trx/game/ui/dialogs/select_level.h>
#include <trx/game/ui/dialogs/sound_settings.h>
#include <trx/game/ui/dialogs/stats.h>
#include <trx/game/ui/dialogs/text.h>
#include <trx/game/ui/draw.h>
#include <trx/game/ui/elements/ammo_label.h>
#include <trx/game/ui/elements/anchor.h>
#include <trx/game/ui/elements/bar.h>
#include <trx/game/ui/elements/bar_enemy_hp.h>
#include <trx/game/ui/elements/bar_lara_air.h>
#include <trx/game/ui/elements/bar_lara_exposure.h>
#include <trx/game/ui/elements/bar_lara_hp.h>
#include <trx/game/ui/elements/bar_lara_sprint.h>
#include <trx/game/ui/elements/button_label.h>
#include <trx/game/ui/elements/color_swatch.h>
#include <trx/game/ui/elements/flash.h>
#include <trx/game/ui/elements/fps_counter.h>
#include <trx/game/ui/elements/frame.h>
#include <trx/game/ui/elements/gradient_slider.h>
#include <trx/game/ui/elements/hide.h>
#include <trx/game/ui/elements/horizontal_line.h>
#include <trx/game/ui/elements/label.h>
#include <trx/game/ui/elements/modal.h>
#include <trx/game/ui/elements/offset.h>
#include <trx/game/ui/elements/pad.h>
#include <trx/game/ui/elements/prompt.h>
#include <trx/game/ui/elements/requester.h>
#include <trx/game/ui/elements/resize.h>
#include <trx/game/ui/elements/row_arrows.h>
#include <trx/game/ui/elements/scrollable_stack.h>
#include <trx/game/ui/elements/spacer.h>
#include <trx/game/ui/elements/span.h>
#include <trx/game/ui/elements/stack.h>
#include <trx/game/ui/elements/window.h>
#include <trx/game/ui/events.h>
#include <trx/game/ui/hud/console.h>
#include <trx/game/ui/hud/console_logs.h>
#include <trx/game/ui/hud/overlay.h>
#include <trx/game/ui/text.h>
