#include "game/vars.h"

#ifdef T1M_FEAT_GAMEPLAY
int16_t StoredLaraHealth = 0;
#endif

#ifdef T1M_FEAT_UI
int16_t BarOffsetY[6];
#endif

char *GF_LevelNames[LV_NUMBER_OF] = {
    "data\\gym.phd",      "data\\level1.phd",   "data\\level2.phd",
    "data\\level3a.phd",  "data\\level3b.phd",  "data\\level4.phd",
    "data\\level5.phd",   "data\\level6.phd",   "data\\level7a.phd",
    "data\\level7b.phd",  "data\\level8a.phd",  "data\\level8b.phd",
    "data\\level8c.phd",  "data\\level10a.phd", "data\\level10b.phd",
    "data\\level10c.phd", "data\\cut1.phd",     "data\\cut2.phd",
    "data\\cut3.phd",     "data\\cut4.phd",     "data\\title.phd",
    "data\\current.phd",
};

char *GF_LevelTitles[LV_NUMBER_OF] = {
    "Lara's Home",
    "Caves",
    "City of Vilcabamba",
    "Lost Valley",
    "Tomb of Qualopec",
    "St. Francis' Folly",
    "Colosseum",
    "Palace Midas",
    "The Cistern",
    "Tomb of Tihocan",
    "City of Khamoon",
    "Obelisk of Khamoon",
    "Sanctuary of the Scion",
    "Natla's Mines",
    "Atlantis",
    "The Great Pyramid",
    "Cut Scene 1",
    "Cut Scene 2",
    "Cut Scene 3",
    "Cut Scene 4",
    "Title",
    "Current Position",
};

char *GF_GameStringTable[GSI_NUMBER_OF] = {
    [GSI_HEADING_INVENTORY] = "INVENTORY",
    [GSI_HEADING_GAME_OVER] = "GAME OVER",
    [GSI_HEADING_OPTION] = "OPTION",
    [GSI_HEADING_ITEMS] = "ITEMS",
    [GSI_PASSPORT_SELECT_LEVEL] = "Select Level",
    [GSI_PASSPORT_SELECT_MODE] = "Select Mode",
    [GSI_PASSPORT_MODE_NEW_GAME] = "New Game",
    [GSI_PASSPORT_MODE_NEW_GAME_PLUS] = "New Game+",
    [GSI_PASSPORT_NEW_GAME] = "New Game",
    [GSI_PASSPORT_LOAD_GAME] = "Load Game",
    [GSI_PASSPORT_SAVE_GAME] = "Save Game",
    [GSI_PASSPORT_EXIT_GAME] = "Exit Game",
    [GSI_PASSPORT_EXIT_TO_TITLE] = "Exit to Title",
    [GSI_DETAIL_SELECT_DETAIL] = "Select Detail",
    [GSI_DETAIL_LEVEL_HIGH] = "High",
    [GSI_DETAIL_LEVEL_MEDIUM] = "Medium",
    [GSI_DETAIL_LEVEL_LOW] = "Low",
    [GSI_DETAIL_PERSPECTIVE_FMT] = "Perspective     %s",
    [GSI_DETAIL_BILINEAR_FMT] = "Bilinear        %s",
    [GSI_DETAIL_VIDEO_MODE_FMT] = "Game Video Mode %s",
    [GSI_SOUND_SET_VOLUMES] = "Set Volumes",
    [GSI_CONTROL_DEFAULT_KEYS] = "Default Keys",
    [GSI_CONTROL_USER_KEYS] = "User Keys",
    [GSI_KEYMAP_RUN] = "Run",
    [GSI_KEYMAP_BACK] = "Back",
    [GSI_KEYMAP_LEFT] = "Left",
    [GSI_KEYMAP_RIGHT] = "Right",
    [GSI_KEYMAP_STEP_LEFT] = "Step Left",
    [GSI_KEYMAP_STEP_RIGHT] = "Step Right",
    [GSI_KEYMAP_WALK] = "Walk",
    [GSI_KEYMAP_JUMP] = "Jump",
    [GSI_KEYMAP_ACTION] = "Action",
    [GSI_KEYMAP_DRAW_WEAPON] = "Draw Weapon",
    [GSI_KEYMAP_LOOK] = "Look",
    [GSI_KEYMAP_ROLL] = "Roll",
    [GSI_KEYMAP_INVENTORY] = "Inventory",
    [GSI_STATS_TIME_TAKEN_FMT] = "TIME TAKEN %s",
    [GSI_STATS_SECRETS_FMT] = "SECRETS %d OF %d",
    [GSI_STATS_PICKUPS_FMT] = "PICKUPS %d",
    [GSI_STATS_KILLS_FMT] = "KILLS %d",
    [GSI_MISC_ON] = "On",
    [GSI_MISC_OFF] = "Off",
    [GSI_MISC_EMPTY_SLOT_FMT] = "- EMPTY SLOT %d -",
    [GSI_MISC_DEMO_MODE] = "Demo Mode",
    [GSI_INV_ITEM_MEDI] = "Small Medi Pack",
    [GSI_INV_ITEM_BIG_MEDI] = "Large Medi Pack",
    [GSI_INV_ITEM_PUZZLE1] = "Puzzle",
    [GSI_INV_ITEM_PUZZLE2] = "Puzzle",
    [GSI_INV_ITEM_PUZZLE3] = "Puzzle",
    [GSI_INV_ITEM_PUZZLE4] = "Puzzle",
    [GSI_INV_ITEM_KEY1] = "Key",
    [GSI_INV_ITEM_KEY2] = "Key",
    [GSI_INV_ITEM_KEY3] = "Key",
    [GSI_INV_ITEM_KEY4] = "Key",
    [GSI_INV_ITEM_PICKUP1] = "Pickup",
    [GSI_INV_ITEM_PICKUP2] = "Pickup",
    [GSI_INV_ITEM_LEADBAR] = "Lead Bar",
    [GSI_INV_ITEM_SCION] = "Scion",
    [GSI_INV_ITEM_PISTOLS] = "Pistols",
    [GSI_INV_ITEM_SHOTGUN] = "Shotgun",
    [GSI_INV_ITEM_MAGNUM] = "Magnums",
    [GSI_INV_ITEM_UZI] = "Uzis",
    [GSI_INV_ITEM_GRENADE] = "Grenade",
    [GSI_INV_ITEM_PISTOL_AMMO] = "Pistol Clips",
    [GSI_INV_ITEM_SHOTGUN_AMMO] = "Shotgun Shells",
    [GSI_INV_ITEM_MAGNUM_AMMO] = "Magnum Clips",
    [GSI_INV_ITEM_UZI_AMMO] = "Uzi Clips",
    [GSI_INV_ITEM_COMPASS] = "Compass",
    [GSI_INV_ITEM_GAME] = "Game",
    [GSI_INV_ITEM_DETAILS] = "Detail Levels",
    [GSI_INV_ITEM_SOUND] = "Sound",
    [GSI_INV_ITEM_CONTROLS] = "Controls",
    [GSI_INV_ITEM_GAMMA] = "Gamma",
    [GSI_INV_ITEM_LARAS_HOME] = "Lara's Home",
};
