<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <AssemblyName>TRX_Installer</AssemblyName>
    <StartupObject>TRX_Installer.Program</StartupObject>
    <ProduceReferenceAssembly>True</ProduceReferenceAssembly>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <PublishReadyToRun>true</PublishReadyToRun>
    <EnableCompressionInSingleFile>false</EnableCompressionInSingleFile>
    <SelfContained>false</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <ApplicationIcon>Resources\icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Remove="App.xaml" />
    <Page Include="App.xaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DiscUtils.Iso9660" Version="0.16.13" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\const.json" />
    <EmbeddedResource Include="Resources\Lang\en.json" />
    <EmbeddedResource Include="Resources\Lang\it.json" />
    <EmbeddedResource Include="Resources\release.zip" Condition="Exists('Resources\release.zip')" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\icon.ico" />
    <Resource Include="Resources\side1.jpg" />
    <Resource Include="Resources\side2.jpg" />
    <Resource Include="Resources\side3.jpg" />
    <Resource Include="Resources\side4.jpg" />
  </ItemGroup>
</Project>
