repos:
- repo: local
  hooks:
  - id: clang-format
    name: clang-format
    entry: clang-format
    args: ["-style=file", "-i"]
    language: system
    files: \.[ch](pp)?$

  - id: additional-lint
    name: Run additional linters
    entry: tools/additional_lint
    language: python
    stages: [commit]

  - id: imports
    name: imports
    entry: tools/sort_imports
    language: system
    files: \.[ch](pp)?$

  - id: update-gameflow
    name: Update game flow files
    entry: tools/update_gameflow
    language: python
    stages: [commit]
