#pragma once

#include <windows.h>

#define _FACDD 0x876
#define MAKE_DDHRESULT(code) MAKE_HRESULT(1, _FACDD, code)

#define DDSD_BACKBUFFERCOUNT 0x00000020
#define DDSD_CAPS 0x00000001
#define DDSD_HEIGHT 0x00000002
#define DDSD_PIXELFORMAT 0x00001000
#define DDSD_WIDTH 0x00000004
#define DDBLT_COLORFILL 0x00000400
#define DDERR_ALREADYINITIALIZED MAKE_DDHRESULT(5)
#define DDERR_GENERIC E_FAIL
#define DDERR_LOCKEDSURFACES MAKE_DDHRESULT(160)
#define DDERR_NOTFLIPPABLE MAKE_DDHRESULT(582)
#define DDERR_NOTLOCKED MAKE_DDHRESULT(584)
#define DDERR_SURFACEBUSY MAKE_DDHRESULT(430)
#define DDERR_SURFACENOTATTACHED MAKE_DDHRESULT(460)
#define DDSCAPS_FLIP 0x00000010
#define DDSCAPS_FRONTBUFFER 0x00000020
#define DDSCAPS_PRIMARYSURFACE 0x00000200
#define DD_OK S_OK

typedef struct _DDSCAPS {
    DWORD dwCaps;
} DDSCAPS, *LPDDSCAPS;

typedef struct _DDPIXELFORMAT {
    DWORD dwFlags;
    DWORD dwRGBBitCount;
} DDPIXELFORMAT, *LPDDPIXELFORMAT;

typedef struct _DDSURFACEDESC {
    DWORD dwFlags;
    DWORD dwHeight;
    DWORD dwWidth;
    LONG lPitch;
    DWORD dwBackBufferCount;
    LPVOID lpSurface;
    DDPIXELFORMAT ddpfPixelFormat;
    DDSCAPS ddsCaps;
} DDSURFACEDESC, *LPDDSURFACEDESC;

typedef void *LPDIRECTDRAWSURFACE;
