project(
  'libtrx',
  'c',
  default_options: [
    'c_std=c2x',
    'warning_level=3',
  ],
  meson_version: '>=1.3.0',
)

staticdeps = get_option('staticdeps')
tr_version = get_option('tr_version')

fs = import('fs')
c_compiler = meson.get_compiler('c')
relative_dir = fs.relative_to(meson.current_source_dir(), meson.global_build_root())
build_opts = [
  # common options
  '-Wno-unused',
  '-Wno-unused-parameter',
  '-Wno-microsoft-anon-tag',
  '-Wno-gnu-binary-literal',
  '-Wno-gnu-empty-initializer',
  '-Wno-gnu-zero-variadic-macro-arguments',
  '-DMESON_BUILD',
  '-DGLEW_NO_GLU',
  '-DSDL_MAIN_HANDLED',
  '-fms-extensions',
  '-fno-omit-frame-pointer',
  # end of common options
  '-fmacro-prefix-map=@0@/=libtrx/'.format(relative_dir),
  '-DDWST_STATIC',
  '-DPCRE2_STATIC',
  '-DPCRE2_CODE_UNIT_WIDTH=8',
  '-DTR_VERSION=' + tr_version.to_string(),
  '-DDEBUG=' + (get_option('buildtype') == 'debug' ? '1' : '0'),
]
set_variable('defines', ['-DTR_VERSION=' + tr_version.to_string()])

add_project_arguments(build_opts, language: 'c')

# Always dynamically link on macOS
if host_machine.system() == 'darwin'
  staticdeps = false
endif

null_dep = dependency('', required: false)
dep_avcodec = dependency('libavcodec', static: staticdeps)
dep_avformat = dependency('libavformat', static: staticdeps)
dep_avutil = dependency('libavutil', static: staticdeps)
dep_sdl2 = dependency('SDL2', static: staticdeps)
dep_glew = dependency('glew', static: staticdeps)
dep_pcre2 = dependency('libpcre2-8', static: staticdeps)
dep_backtrace = c_compiler.find_library('backtrace', static: true, required: false)
dep_swscale = dependency('libswscale', static: staticdeps)
dep_swresample = dependency('libswresample', static: staticdeps)
dep_lua = dependency('lua', static: staticdeps)
c_compiler.check_header('uthash.h', required: true)

dep_zlib = null_dep
if not staticdeps
  dep_zlib = dependency('zlib', static: staticdeps)
endif

if host_machine.system() == 'windows'
  dep_opengl = c_compiler.find_library('opengl32')
else
  dep_opengl = dependency('GL')
endif

sources = [
  'benchmark.c',
  'config/common.c',
  'config/file.c',
  'config/map.c',
  'config/priv.c',
  'config/vars.c',
  'engine/audio.c',
  'engine/audio_sample.c',
  'engine/audio_stream.c',
  'engine/image.c',
  'engine/video.c',
  'enum_map.c',
  'event_manager.c',
  'filesystem.c',
  'game/anims/commands.c',
  'game/anims/common.c',
  'game/anims/frames.c',
  'game/camera/cinematic.c',
  'game/camera/common.c',
  'game/camera/fixed.c',
  'game/camera/photo_mode.c',
  'game/camera/vars.c',
  'game/carrier.c',
  'game/catalog.c',
  'game/clock/common.c',
  'game/clock/timer.c',
  'game/clock/turbo.c',
  'game/collision.c',
  'game/console/cmd/clear.c',
  'game/console/cmd/config.c',
  'game/console/cmd/debug.c',
  'game/console/cmd/die.c',
  'game/console/cmd/easy_config.c',
  'game/console/cmd/end_level.c',
  'game/console/cmd/exit_game.c',
  'game/console/cmd/exit_to_title.c',
  'game/console/cmd/flipmap.c',
  'game/console/cmd/flood.c',
  'game/console/cmd/fly.c',
  'game/console/cmd/give_item.c',
  'game/console/cmd/give_secret.c',
  'game/console/cmd/heal.c',
  'game/console/cmd/help.c',
  'game/console/cmd/immune.c',
  'game/console/cmd/inf_sprint.c',
  'game/console/cmd/kill.c',
  'game/console/cmd/load_game.c',
  'game/console/cmd/lua.c',
  'game/console/cmd/music.c',
  'game/console/cmd/play_cutscene.c',
  'game/console/cmd/play_demo.c',
  'game/console/cmd/play_gym.c',
  'game/console/cmd/play_level.c',
  'game/console/cmd/pos.c',
  'game/console/cmd/save_game.c',
  'game/console/cmd/screenshot.c',
  'game/console/cmd/set_health.c',
  'game/console/cmd/sfx.c',
  'game/console/cmd/speed.c',
  'game/console/cmd/strings.c',
  'game/console/cmd/teleport.c',
  'game/console/cmd/winston.c',
  'game/console/common.c',
  'game/console/history.c',
  'game/console/registry.c',
  'game/creature/common.c',
  'game/demo/common.c',
  'game/events.c',
  'game/fader.c',
  'game/fmv.c',
  'game/game.c',
  'game/game_buf.c',
  'game/game_flow/common.c',
  'game/game_flow/inventory.c',
  'game/game_flow/reader.c',
  'game/game_flow/sequencer.c',
  'game/game_flow/sequencer_events.c',
  'game/game_flow/sequencer_misc.c',
  'game/game_flow/vars.c',
  'game/game_string.c',
  'game/game_string_manager.c',
  'game/game_string_table/common.c',
  'game/game_string_table/priv.c',
  'game/game_string_table/reader.c',
  'game/gun/common.c',
  'game/gun/control.c',
  'game/gun/misc.c',
  'game/gun/pistols.c',
  'game/gun/rifle.c',
  'game/gun/vars.c',
  'game/gym.c',
  'game/inject/common.c',
  'game/inject/data/anims.c',
  'game/inject/data/camera.c',
  'game/inject/data/meshes.c',
  'game/inject/data/objects.c',
  'game/inject/data/sound.c',
  'game/inject/data/textures.c',
  'game/inject/editor.c',
  'game/inject/editors/anims.c',
  'game/inject/editors/floor_data.c',
  'game/inject/editors/meshes.c',
  'game/inject/editors/objects.c',
  'game/inject/editors/positions.c',
  'game/inject/editors/rooms.c',
  'game/inject/editors/textures.c',
  'game/inject/testers/items.c',
  'game/inject/testers/rooms.c',
  'game/inject/utils.c',
  'game/input/backends/controller.c',
  'game/input/backends/internal.c',
  'game/input/backends/keyboard.c',
  'game/input/common.c',
  'game/input/update.c',
  'game/interpolation.c',
  'game/inventory.c',
  'game/inventory_ring/draw.c',
  'game/inventory_ring/priv.c',
  'game/inventory_ring/vars.c',
  'game/items/anim.c',
  'game/items/col.c',
  'game/items/common.c',
  'game/items/utils.c',
  'game/items/walkable.c',
  'game/lara/cheat.c',
  'game/lara/cheat_keys.c',
  'game/lara/col.c',
  'game/lara/col/climb.c',
  'game/lara/col/jump.c',
  'game/lara/col/land.c',
  'game/lara/col/swim.c',
  'game/lara/common.c',
  'game/lara/control.c',
  'game/lara/draw.c',
  'game/lara/flare.c',
  'game/lara/hair.c',
  'game/lara/look.c',
  'game/lara/mesh.c',
  'game/lara/misc.c',
  'game/lara/pose.c',
  'game/lara/state.c',
  'game/lara/state/climb.c',
  'game/lara/state/extra.c',
  'game/lara/state/jump.c',
  'game/lara/state/land.c',
  'game/lara/state/swim.c',
  'game/lara/vehicle.c',
  'game/level/common.c',
  'game/level/faces.c',
  'game/level/reader.c',
  'game/level/reader_tr1.c',
  'game/level/reader_tr2.c',
  'game/level/settings.c',
  'game/los.c',
  'game/lua/common.c',
  'game/lua/config.c',
  'game/lua/console.c',
  'game/lua/events.c',
  'game/lua/items.c',
  'game/lua/lara.c',
  'game/lua/log.c',
  'game/lua/music.c',
  'game/lua/sound.c',
  'game/math/trig.c',
  'game/math/util.c',
  'game/matrix.c',
  'game/music/backend_cdaudio.c',
  'game/music/backend_files.c',
  'game/music/common.c',
  'game/music/ids.c',
  'game/objects/col.c',
  'game/objects/common.c',
  'game/objects/creatures/ape.c',
  'game/objects/creatures/bacon_lara.c',
  'game/objects/creatures/baldy.c',
  'game/objects/creatures/bandit_1.c',
  'game/objects/creatures/bandit_2.c',
  'game/objects/creatures/barracuda.c',
  'game/objects/creatures/bartoli.c',
  'game/objects/creatures/bat.c',
  'game/objects/creatures/bear.c',
  'game/objects/creatures/big_eel.c',
  'game/objects/creatures/big_spider.c',
  'game/objects/creatures/bird.c',
  'game/objects/creatures/bird_guardian.c',
  'game/objects/creatures/centaur.c',
  'game/objects/creatures/centaur_statue.c',
  'game/objects/creatures/cowboy.c',
  'game/objects/creatures/crocodile.c',
  'game/objects/creatures/cultist_1.c',
  'game/objects/creatures/cultist_2.c',
  'game/objects/creatures/cultist_3.c',
  'game/objects/creatures/diver.c',
  'game/objects/creatures/dog.c',
  'game/objects/creatures/dragon.c',
  'game/objects/creatures/eel.c',
  'game/objects/creatures/jelly.c',
  'game/objects/creatures/larson.c',
  'game/objects/creatures/lion.c',
  'game/objects/creatures/monk.c',
  'game/objects/creatures/mouse.c',
  'game/objects/creatures/mummy.c',
  'game/objects/creatures/mutant.c',
  'game/objects/creatures/natla.c',
  'game/objects/creatures/pierre.c',
  'game/objects/creatures/pod.c',
  'game/objects/creatures/raptor.c',
  'game/objects/creatures/rat.c',
  'game/objects/creatures/shark.c',
  'game/objects/creatures/skate_kid.c',
  'game/objects/creatures/spider.c',
  'game/objects/creatures/tiger.c',
  'game/objects/creatures/torso.c',
  'game/objects/creatures/trex.c',
  'game/objects/creatures/winston.c',
  'game/objects/creatures/wolf.c',
  'game/objects/creatures/worker_1.c',
  'game/objects/creatures/worker_2.c',
  'game/objects/creatures/worker_3.c',
  'game/objects/creatures/xian_common.c',
  'game/objects/creatures/xian_knight.c',
  'game/objects/creatures/xian_spearman.c',
  'game/objects/creatures/yeti.c',
  'game/objects/draw.c',
  'game/objects/effects/blood.c',
  'game/objects/effects/body_part.c',
  'game/objects/effects/bubble.c',
  'game/objects/effects/dart_effect.c',
  'game/objects/effects/ember.c',
  'game/objects/effects/explosion.c',
  'game/objects/effects/flame.c',
  'game/objects/effects/glow.c',
  'game/objects/effects/gun_flash.c',
  'game/objects/effects/hot_liquid.c',
  'game/objects/effects/missile.c',
  'game/objects/effects/missile_common.c',
  'game/objects/effects/missile_flame.c',
  'game/objects/effects/missile_harpoon.c',
  'game/objects/effects/missile_knife.c',
  'game/objects/effects/natla_gun.c',
  'game/objects/effects/pickup_aid.c',
  'game/objects/effects/ricochet.c',
  'game/objects/effects/snow_sprite.c',
  'game/objects/effects/splash.c',
  'game/objects/effects/twinkle.c',
  'game/objects/effects/water_sprite.c',
  'game/objects/general/alarm_sound.c',
  'game/objects/general/bell.c',
  'game/objects/general/big_bowl.c',
  'game/objects/general/bird_tweeter.c',
  'game/objects/general/boat.c',
  'game/objects/general/bridge_common.c',
  'game/objects/general/bridge_flat.c',
  'game/objects/general/bridge_tilt1.c',
  'game/objects/general/bridge_tilt2.c',
  'game/objects/general/cabin.c',
  'game/objects/general/camera_target.c',
  'game/objects/general/clock_chimes.c',
  'game/objects/general/cog.c',
  'game/objects/general/copter.c',
  'game/objects/general/detonator_box.c',
  'game/objects/general/ding_dong.c',
  'game/objects/general/door.c',
  'game/objects/general/drawbridge.c',
  'game/objects/general/general.c',
  'game/objects/general/gong.c',
  'game/objects/general/gong_bonger.c',
  'game/objects/general/grenade.c',
  'game/objects/general/keyhole.c',
  'game/objects/general/lara_alarm.c',
  'game/objects/general/lift.c',
  'game/objects/general/mini_copter.c',
  'game/objects/general/moving_bar.c',
  'game/objects/general/puzzle_hole.c',
  'game/objects/general/scion1.c',
  'game/objects/general/scion3.c',
  'game/objects/general/scion4.c',
  'game/objects/general/scion_holder.c',
  'game/objects/general/sphere_of_doom.c',
  'game/objects/general/trapdoor.c',
  'game/objects/general/waterfall.c',
  'game/objects/general/window.c',
  'game/objects/names.c',
  'game/objects/traps/blade.c',
  'game/objects/traps/dart.c',
  'game/objects/traps/dart_emitter.c',
  'game/objects/traps/dying_monk.c',
  'game/objects/traps/ember_emitter.c',
  'game/objects/traps/falling_block.c',
  'game/objects/traps/falling_ceiling.c',
  'game/objects/traps/flame_emitter.c',
  'game/objects/traps/gondola.c',
  'game/objects/traps/hook.c',
  'game/objects/traps/icicle.c',
  'game/objects/traps/killer_statue.c',
  'game/objects/traps/lava_wedge.c',
  'game/objects/traps/midas_touch.c',
  'game/objects/traps/mine.c',
  'game/objects/traps/movable_block.c',
  'game/objects/traps/pendulum.c',
  'game/objects/traps/power_saw.c',
  'game/objects/traps/propeller.c',
  'game/objects/traps/rolling_ball.c',
  'game/objects/traps/sliding_pillar.c',
  'game/objects/traps/spike_ceiling.c',
  'game/objects/traps/spike_wall.c',
  'game/objects/traps/spikes.c',
  'game/objects/traps/spinning_blade.c',
  'game/objects/traps/springboard.c',
  'game/objects/traps/teeth_trap.c',
  'game/objects/traps/thors_hammer.c',
  'game/objects/vars.c',
  'game/option/common.c',
  'game/option/controls.c',
  'game/option/examine.c',
  'game/option/gameplay.c',
  'game/option/graphics.c',
  'game/option/sound.c',
  'game/output/background.c',
  'game/output/common.c',
  'game/output/draw.c',
  'game/output/func.c',
  'game/output/lights.c',
  'game/output/mesh_batcher/batcher.c',
  'game/output/mesh_batcher/mesh.c',
  'game/output/mesh_batcher/mesh_builder.c',
  'game/output/scene_compositor.c',
  'game/output/shader.c',
  'game/output/sources/background.c',
  'game/output/sources/lightnings.c',
  'game/output/sources/misc.c',
  'game/output/sources/objects.c',
  'game/output/sources/rooms.c',
  'game/output/sources/rooms_debug.c',
  'game/output/sources/shadows.c',
  'game/output/sources/sprites.c',
  'game/output/sources/ui.c',
  'game/output/state.c',
  'game/output/textures.c',
  'game/output/vertex_range.c',
  'game/output/warmup.c',
  'game/overlay.c',
  'game/packer.c',
  'game/pathing/box.c',
  'game/pathing/lot.c',
  'game/pathing/vars.c',
  'game/phase/executor.c',
  'game/phase/phase_cutscene.c',
  'game/phase/phase_demo.c',
  'game/phase/phase_game.c',
  'game/phase/phase_inventory.c',
  'game/phase/phase_pause.c',
  'game/phase/phase_photo_mode.c',
  'game/phase/phase_picture.c',
  'game/phase/phase_stats.c',
  'game/photo_mode.c',
  'game/random.c',
  'game/rooms/common.c',
  'game/rooms/draw.c',
  'game/rooms/floor_data.c',
  'game/rooms/geometry.c',
  'game/savegame/common.c',
  'game/scaler.c',
  'game/shell/args.c',
  'game/shell/common.c',
  'game/shell/config.c',
  'game/shell/events.c',
  'game/shell/flow.c',
  'game/shell/input.c',
  'game/shell/main.c',
  'game/shell/platform.c',
  'game/sound/common.c',
  'game/sound/ids.c',
  'game/spawn.c',
  'game/stats.c',
  'game/test_recorder.c',
  'game/test_replay.c',
  'game/ui/common.c',
  'game/ui/dialogs/base_passport.c',
  'game/ui/dialogs/controls.c',
  'game/ui/dialogs/controls_backend.c',
  'game/ui/dialogs/controls_editor.c',
  'game/ui/dialogs/gameplay_settings.c',
  'game/ui/dialogs/graphic_settings.c',
  'game/ui/dialogs/new_game.c',
  'game/ui/dialogs/pause.c',
  'game/ui/dialogs/photo_mode.c',
  'game/ui/dialogs/play_any_level.c',
  'game/ui/dialogs/save_slot.c',
  'game/ui/dialogs/select_level.c',
  'game/ui/dialogs/setting_helpers/enums.c',
  'game/ui/dialogs/setting_helpers/handlers.c',
  'game/ui/dialogs/setting_helpers/handlers_language.c',
  'game/ui/dialogs/settings.c',
  'game/ui/dialogs/sound_settings.c',
  'game/ui/dialogs/stats.c',
  'game/ui/dialogs/text.c',
  'game/ui/draw.c',
  'game/ui/elements/ammo_label.c',
  'game/ui/elements/anchor.c',
  'game/ui/elements/bar.c',
  'game/ui/elements/bar_enemy_hp.c',
  'game/ui/elements/bar_lara_air.c',
  'game/ui/elements/bar_lara_exposure.c',
  'game/ui/elements/bar_lara_hp.c',
  'game/ui/elements/bar_lara_sprint.c',
  'game/ui/elements/button_label.c',
  'game/ui/elements/fade.c',
  'game/ui/elements/fixed.c',
  'game/ui/elements/flash.c',
  'game/ui/elements/fps_counter.c',
  'game/ui/elements/frame.c',
  'game/ui/elements/hide.c',
  'game/ui/elements/label.c',
  'game/ui/elements/modal.c',
  'game/ui/elements/offset.c',
  'game/ui/elements/pad.c',
  'game/ui/elements/progress_button.c',
  'game/ui/elements/prompt.c',
  'game/ui/elements/requester.c',
  'game/ui/elements/resize.c',
  'game/ui/elements/row_arrows.c',
  'game/ui/elements/scrollable_area.c',
  'game/ui/elements/spacer.c',
  'game/ui/elements/span.c',
  'game/ui/elements/stack.c',
  'game/ui/elements/tab_switch.c',
  'game/ui/elements/window.c',
  'game/ui/events.c',
  'game/ui/helpers.c',
  'game/ui/hud/console.c',
  'game/ui/hud/console_logs.c',
  'game/ui/hud/overlay.c',
  'game/ui/scrollable.c',
  'game/ui/text.c',
  'game/viewport.c',
  'gfx/2d/2d_renderer.c',
  'gfx/2d/2d_surface.c',
  'gfx/context.c',
  'gfx/gl/buffer.c',
  'gfx/gl/fbo.c',
  'gfx/gl/program.c',
  'gfx/gl/sampler.c',
  'gfx/gl/texture.c',
  'gfx/gl/track.c',
  'gfx/gl/utils.c',
  'gfx/gl/vertex_array.c',
  'gfx/renderer.c',
  'gfx/screenshot.c',
  'json/bson_parse.c',
  'json/bson_write.c',
  'json/json_base.c',
  'json/json_parse.c',
  'json/json_write.c',
  'json_file.c',
  'log.c',
  'memory.c',
  'screenshot.c',
  'strings/case_funcs.c',
  'strings/common.c',
  'strings/fuzzy_match.c',
  'thread_pool.c',
  'vector.c',
  'virtual_file.c',
]

dependencies = [
  dep_avcodec,
  dep_avformat,
  dep_avutil,
  dep_sdl2,
  dep_glew,
  dep_pcre2,
  dep_backtrace,
  dep_swresample,
  dep_swscale,
  dep_lua,
  dep_zlib,
  dep_opengl,
]

if dep_backtrace.found() and host_machine.system() == 'linux'
  sources += ['log_linux.c']
elif host_machine.system() == 'windows'
  sources += ['log_windows.c']
  dwarfstack = subproject('dwarfstack', default_options: ['warning_level=0'])
  dep_dwarfstack = dwarfstack.get_variable('dep_dwarfstack')
  dep_dbghelp = c_compiler.find_library('dbghelp')
  dependencies += [dep_dbghelp, dep_dwarfstack]
else
  sources += ['log_unknown.c']
endif

libtrx = static_library(
  'libtrx',
  sources,
  dependencies: dependencies,
  include_directories: ['.', 'include/libtrx/'],
)

dep_trx = declare_dependency(
  link_whole: libtrx,
  include_directories: [
    include_directories('include/', is_system: true)
  ]
)
