-- Argument checking for the whole of trx.*, and the seal that closes the API.
--
-- What each member takes is written as annotations next to its code. The build
-- reads them into trx.internal.signatures, and strict mode checks calls against
-- that:
-- api.strict rebinds every function, method and callable namespace to a
-- closure that checks what it was handed. With checking off, nothing wraps
-- them at all.

-- Captured at module scope: the raw C bridge is removed from the globals once
-- the trx.* modules have loaded.
local struct = trxc.struct
local capi = trxc.api

local check = require("trx.internal.check")
local h = require("trx.internal.helpers")

-- What the annotated modules take, generated by the build. Absent where only
-- part of the surface is stood up.
---@type trx.internal.signatures
local signatures = require("trx.internal.signatures")
  or {
    functions = {},
    calls = {},
    methods = {},
    types = {},
    records = {},
    properties = {},
    containers = {},
    members = {},
    writable = {},
    constants = {},
  }

---@class (partial) trx
---@field api trx.api

---Argument checking for the whole of `trx`.
---@trx.module 38 Argument checking
---@class (exact) trx.api
local M = h.module("api")

local strict_enabled = false

local function segments(path)
  local parts = {}
  for segment in tostring(path):gmatch("[^.]+") do
    parts[#parts + 1] = segment
  end
  return parts
end

-- The table at a dotted path under trx, or nil where it is not loaded, as
-- where a test stands up part of the surface.
local function table_at(path)
  local tbl = trx
  for _, part in ipairs(segments(path)) do
    tbl = tbl ~= nil and rawget(tbl, part) or nil
  end
  return tbl
end

-- What checks a value against a declaration is asked the first time it is
-- needed and kept on the declaration: a declaration may name a type that a
-- module further down the load order declares.
local function once(holder, slot, answer, declared)
  local held = holder[slot]
  if held == nil then
    held = answer(declared)
    holder[slot] = held
  end
  return held
end

-- A type this surface does not declare waves every value through. The seal
-- reports the name itself.
local function checker(declared)
  return check.of(declared) or check.anything
end

-- Strict mode wraps the implementation in a closure that checks what it was
-- handed. `select` reads the arguments without copying them, and handing `...`
-- straight on keeps the count the caller gave: several bridges read
-- lua_gettop() to tell "not given" from "given nil", so an optional argument
-- nobody passed has to stay absent rather than arrive as nil.
local function make_checked(fn, path, params)
  if params == nil or #params == 0 then
    return fn
  end

  local variadic = params[#params].name == "..."
  local fixed = variadic and #params - 1 or #params

  local names, optional, predicates, defaults, labels = {}, {}, {}, {}, {}
  local fills_a_default = false
  for i = 1, fixed do
    local p = params[i]
    names[i] = p.name
    optional[i] = p.optional == true
    predicates[i] = checker(p)
    defaults[i] = p.default
    -- What the argument had to be, for a predicate that answers yes or no and
    -- has nothing of its own to say: a handle, a class, and every primitive.
    labels[i] = "expected " .. check.label_of(p)
    if p.default ~= nil then
      fills_a_default = true
    end
  end

  -- Three frames down to the caller: here, the wrapper, and whoever called it.
  local function checked(i, value)
    if value == nil and optional[i] then
      return
    end
    local ok, why = predicates[i](value)
    if not ok then
      error(
        ("%s: invalid argument '%s' - %s"):format(
          path,
          names[i],
          why or labels[i]
        ),
        3
      )
    end
  end

  if not fills_a_default then
    return function(...)
      for i = 1, fixed do
        checked(i, (select(i, ...)))
      end
      return fn(...)
    end
  end

  -- Substituting a default hands the implementation a different argument list
  -- than the caller wrote, so this one has to build one.
  return function(...)
    local args = table.pack(...)
    for i = 1, fixed do
      if args[i] == nil and defaults[i] ~= nil then
        args[i] = defaults[i]
        if args.n < i then
          args.n = i
        end
      else
        checked(i, args[i])
      end
    end
    return fn(table.unpack(args, 1, args.n))
  end
end

-- The function a caller reaches: the checking wrapper under strict mode, the
-- raw one otherwise.
local function bound(fn, path, params)
  return strict_enabled and make_checked(fn, path, params) or fn
end

-- A method is called with the handle as its first argument, which the
-- annotations do not name because a script never writes it. Checking it
-- catches `item.distance_to(pos)` - a dot where a colon was meant.
local function method_params(params, type_name)
  local out = { { name = "self", type = type_name } }
  for i, param in ipairs(params or {}) do
    out[i + 1] = param
  end
  return out
end

-- A default that names a C constant is generated as a function, read once the
-- modules have loaded.
local function with_defaults(params)
  local out = {}
  for i, param in ipairs(params) do
    if type(param.default) == "function" then
      local copy = {}
      for key, value in pairs(param) do
        copy[key] = value
      end
      local ok, value = pcall(param.default)
      if ok then
        copy.default = value
      else
        copy.default = nil
      end
      param = copy
    end
    out[i] = param
  end
  return out
end

local function strict_failure(path, spec, why)
  return ("%s: %s"):format(path, why or ("expected " .. check.label_of(spec)))
end

-- What the modules held before strict mode wrapped it, keyed by path.
local unwrapped = {}

-- Rebinds what the modules hand a script - their functions, the methods of
-- their types, the calls of their namespaces - to (or away from) a checking
-- wrapper, and checks what a script writes to a property or indexes a
-- collection with.
local function bind()
  for path, params in pairs(signatures.functions) do
    local owner, name = path:match("^(.*)%.([^.]+)$")
    local tbl = table_at(owner)
    unwrapped[path] = unwrapped[path] or (tbl ~= nil and rawget(tbl, name))
    if unwrapped[path] then
      rawset(tbl, name, bound(unwrapped[path], path, with_defaults(params)))
    end
  end
  for path, params in pairs(signatures.calls) do
    local state = h.callables()[path]
    if state ~= nil then
      unwrapped[path] = unwrapped[path] or state.call
      state.call = bound(unwrapped[path], path, with_defaults(params))
    end
  end
  for path, params in pairs(signatures.methods) do
    local owner, name = path:match("^(.*)%.([^.]+)$")
    assert(owner ~= nil and name ~= nil, path)
    local checked = method_params(with_defaults(params), owner)
    local handle = h.handles()[owner]
    local class = h.classes()[owner]
    if handle ~= nil then
      local impl = handle.methods[name]
      local exposed = impl
      if strict_enabled then
        if type(impl) == "string" then
          impl = struct.method(handle.backing, impl)
        end
        exposed = make_checked(impl, path, checked)
      end
      struct.expose_method(handle.backing, name, exposed)
    elseif class ~= nil then
      unwrapped[path] = unwrapped[path] or rawget(class.class, name)
      rawset(class.class, name, bound(unwrapped[path], path, checked))
    end
  end

  if not strict_enabled then
    h.write_check = nil
    h.key_check = nil
    return
  end
  h.write_check = function(path, value)
    local spec = signatures.properties[path]
    if spec == nil or (value == nil and spec.optional) then
      return
    end
    local ok, why = once(spec, "write_check", checker, spec)(value)
    if not ok then
      error(strict_failure("trx." .. path, spec, why), 3)
    end
  end
  h.key_check = function(path, key)
    local spec = signatures.containers[path]
    if spec == nil then
      return
    end
    if not once(spec, "key_check", checker, spec)(key) then
      error(
        ("trx.%s[%s]: expected %s"):format(
          path,
          tostring(key),
          check.label_of(spec)
        ),
        3
      )
    end
  end
end

-- What a type name is checked by: a handle by its C type, a class by
-- identity, a record by the keys it names, and a number, a unit or an enum by
-- the value it stands for.
local function lookup(path)
  local handle = h.handles()[path]
  if handle ~= nil then
    return check.by_metatable(handle.backing)
  end
  local class = h.classes()[path]
  if class ~= nil then
    return check.by_identity(class.class)
  end
  local fields = signatures.records[path]
  if fields ~= nil then
    return check.by_keys(fields)
  end
  local primitive = signatures.types[path]
  return primitive ~= nil and check.primitive(primitive) or nil
end

---Turns argument checking on or off for every function in `trx`, and for the
---methods on its handles. Off by default: checking costs a couple of hundred
---nanoseconds a call, which a per-frame handler notices. Turn it on while
---writing a level, and leave it off in play.
---
---```lua
---trx.api.strict(true)
---```
---@param enabled boolean Whether to check.
function M.strict(enabled)
  strict_enabled = enabled and true or false
  bind()
end

---Whether argument checking is on.
---@return boolean # False as the game starts, and true once something turns it on.
function M.is_strict()
  return strict_enabled
end

-- What the annotations declare is what the module tables hold: anything else
-- reachable on one has no place in the reference, and anything the reference
-- describes has to be there. `partial` is for a test that stands up part of
-- the surface, where a member another module adds is expected to be missing.
local function audit_members(partial)
  local undeclared, missing = {}, {}
  for owner, names in pairs(signatures.members) do
    local tbl = table_at(owner)
    if tbl ~= nil then
      local declared = {}
      for _, name in ipairs(names) do
        declared[name] = true
        if not partial and rawget(tbl, name) == nil then
          missing[#missing + 1] = "trx." .. owner .. "." .. name
        end
      end
      for name in next, tbl do
        if not declared[name] then
          undeclared[#undeclared + 1] = "trx." .. owner .. "." .. name
        end
      end
    end
  end
  local problems = {}
  if #undeclared > 0 then
    table.sort(undeclared)
    problems[#problems + 1] = table.concat(undeclared, ", ")
      .. ": reachable from scripts but not annotated, so the reference "
      .. "cannot describe it."
  end
  if #missing > 0 then
    table.sort(missing)
    problems[#problems + 1] = table.concat(missing, ", ")
      .. ": annotated but not defined, so the reference describes what a "
      .. "script cannot reach."
  end
  if #problems > 0 then
    error(table.concat(problems, "\n"))
  end
end

-- What the annotations say about a member has to be what the modules built:
-- a property or a field takes a write exactly where it is not annotated
-- read-only, and a constant holds the value the reference prints.
local function audit_annotations(partial)
  local reflected = h.reflected()
  local wrong = {}
  local function compare(owner, name, said, found)
    if said == nil and found == false and not partial then
      wrong[#wrong + 1] = (
        "trx.%s.%s takes no write, so it needs annotating "
        .. "read-only"
      ):format(owner, name)
    elseif said == nil and found == true and not partial then
      wrong[#wrong + 1] = ("trx.%s.%s takes a write, but it is not annotated"):format(
        owner,
        name
      )
    elseif said == false and found == true then
      wrong[#wrong + 1] = ("trx.%s.%s takes a write, so it is not read-only"):format(
        owner,
        name
      )
    elseif said == true and found == false then
      wrong[#wrong + 1] = (
        "trx.%s.%s takes no write, so it needs annotating "
        .. "read-only"
      ):format(owner, name)
    elseif said ~= nil and found == nil and not partial then
      wrong[#wrong + 1] = ("trx.%s.%s is annotated, but the module does not build it"):format(
        owner,
        name
      )
    end
  end

  local built = {}
  local function collect(owner, name, takes)
    built[owner] = built[owner] or {}
    built[owner][name] = takes
  end
  for path, takes in pairs(reflected.properties) do
    local owner, name = path:match("^(.*)%.([^.]+)$")
    collect(owner, name, takes)
  end
  for _, group in ipairs({ reflected.fields, reflected.class_fields }) do
    for owner, found in pairs(group) do
      for name, takes in pairs(found) do
        collect(owner, name, takes)
      end
    end
  end

  for owner, found in pairs(built) do
    local said = signatures.writable[owner] or {}
    for name, takes in pairs(found) do
      compare(owner, name, said[name], takes)
    end
  end
  -- A class can hold a field as plain data, which leaves no trace in what the
  -- helpers reflect, so only a read-only one has to be guarded.
  for owner, said in pairs(signatures.writable) do
    local found = built[owner] or {}
    local class = reflected.class_fields[owner] ~= nil
    for name, takes in pairs(said) do
      if found[name] == nil and not (class and takes) then
        compare(owner, name, takes, nil)
      end
    end
  end
  for path, value in pairs(reflected.constants) do
    local said = signatures.constants[path]
    if said ~= nil and said ~= value then
      wrong[#wrong + 1] = ("trx.%s is %s, but the annotations say %s"):format(
        path,
        tostring(value),
        tostring(said)
      )
    end
  end

  if #wrong > 0 then
    table.sort(wrong)
    error(table.concat(wrong, "\n"))
  end
end

-- A type nothing can check waves every value through while strict mode
-- reports a clean run over it. `partial` is for a test that stands up part of
-- the surface, where a name the rest of it declares is expected to be missing.
local function audit_types(partial)
  local bad = {}
  local function report(fmt, ...)
    bad[#bad + 1] = fmt:format(...)
  end

  local function checked_by(where, what, spec)
    local predicate = check.of(spec)
    if predicate == nil and not partial then
      report(
        "%s: %s has an unknown type '%s'",
        where,
        what,
        check.label_of(spec)
      )
    end
    return predicate
  end

  local function audit_params(where, params)
    for _, p in ipairs(params) do
      if p.name ~= "..." then
        local predicate = checked_by(where, ("'%s'"):format(p.name), p)
        local default = p.default
        if type(default) == "function" then
          local ok, value = pcall(default)
          if ok then
            default = value
          else
            default = nil
          end
        end
        if predicate ~= nil and default ~= nil and not predicate(default) then
          report(
            "%s: the default for '%s' is not %s",
            where,
            p.name,
            check.label_of(p)
          )
        end
      end
    end
  end

  for _, group in ipairs({ "functions", "calls", "methods" }) do
    for path, params in pairs(signatures[group]) do
      audit_params(path, params)
    end
  end
  for path, spec in pairs(signatures.properties) do
    checked_by(path, "the property", spec)
  end
  for path, spec in pairs(signatures.containers) do
    checked_by(path, "the key", spec)
  end

  if #bad > 0 then
    table.sort(bad)
    error(table.concat(bad, "\n"))
  end
end

-- Called once, from C, after the trx.* modules have loaded.
local function seal(spec)
  local partial = spec ~= nil and spec.partial == true
  audit_members(partial)
  audit_annotations(partial)
  audit_types(partial)
end

check.reads_from(lookup)

-- Sealing stays C's to call, and is no part of what a script reaches.
capi.set_entrypoint("seal", seal)
