#pragma once

typedef enum {
    AM_4_3,
    AM_16_9,
    AM_16_10,
    AM_ANY,
} ASPECT_MODE;

typedef enum {
    BK_NONE,
    BK_TRANSPARENT_MEDIUM,
    BK_TRANSPARENT_DARK,
    BK_PATTERN_STATIC,
    BK_PATTERN_WAVE,
    BK_IMAGE,
    BK_MONOCHROME,
} BACKGROUND_TYPE;

typedef enum {
    BL_TOP_LEFT,
    BL_TOP_CENTER,
    BL_TOP_RIGHT,
    BL_BOTTOM_LEFT,
    BL_BOTTOM_CENTER,
    BL_BOTTOM_RIGHT,
    BL_CUSTOM,
} BAR_LOCATION;

typedef enum {
    BSM_NEVER,
    BSM_ALWAYS,
    BSM_BOSS_ONLY,
} BAR_SHOW_MODE;

typedef enum {
    MUSIC_LOAD_NEVER,
    MUSIC_LOAD_NON_AMBIENT,
    MUSIC_LOAD_ALWAYS,
} MUSIC_LOAD_CONDITION;

typedef enum {
    UI_STYLE_PS1,
    UI_STYLE_PC,
} UI_STYLE;

typedef enum {
    CAMERA_MODE_TR1,
    CAMERA_MODE_TR2,
    CAMERA_MODE_TR3,
    CAMERA_MODE_NUMBER_OF,
} CAMERA_MODE;

typedef enum {
    WALL_GLITCH_FIXED,
    WALL_GLITCH_TR1,
    WALL_GLITCH_TR2,
} WALL_GLITCH_MODE;

typedef enum {
    JUMP_LOCK_LEGACY,
    JUMP_LOCK_TUNED,
    JUMP_LOCK_DISABLED,
    JUMP_LOCK_NUMBER_OF,
} JUMP_LOCK_MODE;

typedef enum {
    LOOK_MODE_RESTRICTED,
    LOOK_MODE_ENHANCED,
    LOOK_MODE_UNRESTRICTED,
} LOOK_MODE;

typedef enum {
    QUICK_GUNS_DRAW_ONLY,
    QUICK_GUNS_DRAW_AND_HOLSTER,
} QUICK_GUNS_MODE;

typedef enum {
    LIGHTING_CONTRAST_LOW,
    LIGHTING_CONTRAST_MEDIUM,
    LIGHTING_CONTRAST_HIGH,
    LIGHTING_CONTRAST_NUMBER_OF,
} LIGHTING_CONTRAST;

typedef enum {
    BILLBOARD_LOCK_NONE,
    BILLBOARD_LOCK_ROLL,
    BILLBOARD_LOCK_ROLL_PITCH,
    BILLBOARD_LOCK_PERSPECTIVE,
    BILLBOARD_LOCK_NUMBER_OF,
} BILLBOARD_LOCK_MODE;

typedef enum {
    TLM_FULL,
    TLM_SEMI,
    TLM_NONE,
} TARGET_LOCK_MODE;

typedef enum {
    SDM_MINIMAL,
    SDM_DETAILED,
    SDM_FULL,
} STAT_DETAIL_MODE;

typedef enum {
    SHADOW_TYPE_OCTAGON,
    SHADOW_TYPE_CIRCLE,
    SHADOW_TYPE_SPRITE,
    SHADOW_TYPE_NUMBER_OF,
} SHADOW_TYPE;

typedef enum {
    ALLY_HOSTILITY_POLICY_INDIVIDUAL,
    ALLY_HOSTILITY_POLICY_SHARED,
} ALLY_HOSTILITY_POLICY;

typedef enum {
    PROJECTILE_AREA_DAMAGE_SINGLE_SWEEP,
    PROJECTILE_AREA_DAMAGE_MULTI_SWEEP,
} PROJECTILE_AREA_DAMAGE;
