#include "game/ui/dialogs/setting_helpers/enums.h"

#include "config.h"
#include "game/lara/const.h"

#if TR_VERSION == 1
const UI_SETTINGS_ENUM_ENTRY UI_Settings_StatDetailModeEnumEntries[] = {
    { SDM_MINIMAL, GS_ID(GAMEPLAY_SETTINGS_STAT_DETAIL_MODE_MINIMAL) },
    { SDM_DETAILED, GS_ID(GAMEPLAY_SETTINGS_STAT_DETAIL_MODE_DETAILED) },
    { SDM_FULL, GS_ID(GAMEPLAY_SETTINGS_STAT_DETAIL_MODE_FULL) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_TargetModeEnumEntries[] = {
    { TLM_FULL, GS_ID(GAMEPLAY_SETTINGS_TARGET_LOCK_MODE_FULL) },
    { TLM_SEMI, GS_ID(GAMEPLAY_SETTINGS_TARGET_LOCK_MODE_SEMI) },
    { TLM_NONE, GS_ID(GAMEPLAY_SETTINGS_TARGET_LOCK_MODE_NONE) },
    { -1, nullptr },
};
#endif

const UI_SETTINGS_ENUM_ENTRY UI_Settings_WallGlitchEnumEntries[] = {
    { WALL_GLITCH_FIXED, GS_ID(GAMEPLAY_SETTINGS_WALL_GLITCH_FIXED) },
    { WALL_GLITCH_TR1, GS_ID(GAMEPLAY_SETTINGS_WALL_GLITCH_TR1) },
    { WALL_GLITCH_TR2, GS_ID(GAMEPLAY_SETTINGS_WALL_GLITCH_TR2) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_HealthBarShowModeEnumEntries[] = {
    { BSM_DEFAULT, GS_ID(GRAPHIC_SETTINGS_BAR_MODE_DEFAULT) },
    { BSM_PS1, GS_ID(GRAPHIC_SETTINGS_BAR_MODE_PS1) },
    { BSM_FLASHING_OR_DEFAULT,
      GS_ID(GRAPHIC_SETTINGS_BAR_MODE_FLASHING_OR_DEFAULT) },
    { BSM_FLASHING_ONLY, GS_ID(GRAPHIC_SETTINGS_BAR_MODE_FLASHING_ONLY) },
    { BSM_ALWAYS, GS_ID(GRAPHIC_SETTINGS_BAR_MODE_ALWAYS) },
    { BSM_NEVER, GS_ID(GRAPHIC_SETTINGS_BAR_MODE_NEVER) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_AirBarShowModeEnumEntries[] = {
    { BSM_DEFAULT, GS_ID(GRAPHIC_SETTINGS_BAR_MODE_DEFAULT) },
    { BSM_PS1, GS_ID(GRAPHIC_SETTINGS_BAR_MODE_PS1) },
    { BSM_FLASHING_ONLY, GS_ID(GRAPHIC_SETTINGS_BAR_MODE_FLASHING_ONLY) },
    { BSM_NEVER, GS_ID(GRAPHIC_SETTINGS_BAR_MODE_NEVER) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_EnemyHealthBarShowModeEnumEntries[] = {
    { BSM_ALWAYS, GS_ID(GRAPHIC_SETTINGS_BAR_MODE_ALWAYS) },
    { BSM_NEVER, GS_ID(GRAPHIC_SETTINGS_BAR_MODE_NEVER) },
    { BSM_BOSS_ONLY, GS_ID(GRAPHIC_SETTINGS_BAR_MODE_BOSS_ONLY) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_BarLocationEnumEntries[] = {
    { BL_TOP_LEFT, GS_ID(GRAPHIC_SETTINGS_BAR_LOCATION_TOP_LEFT) },
    { BL_TOP_CENTER, GS_ID(GRAPHIC_SETTINGS_BAR_LOCATION_TOP_CENTER) },
    { BL_TOP_RIGHT, GS_ID(GRAPHIC_SETTINGS_BAR_LOCATION_TOP_RIGHT) },
    { BL_BOTTOM_LEFT, GS_ID(GRAPHIC_SETTINGS_BAR_LOCATION_BOTTOM_LEFT) },
    { BL_BOTTOM_CENTER, GS_ID(GRAPHIC_SETTINGS_BAR_LOCATION_BOTTOM_CENTER) },
    { BL_BOTTOM_RIGHT, GS_ID(GRAPHIC_SETTINGS_BAR_LOCATION_BOTTOM_RIGHT) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_BarColorEnumEntries[] = {
    { BC_GOLD, GS_ID(GRAPHIC_SETTINGS_BAR_COLOR_GOLD) },
    { BC_BLUE, GS_ID(GRAPHIC_SETTINGS_BAR_COLOR_BLUE) },
    { BC_GREY, GS_ID(GRAPHIC_SETTINGS_BAR_COLOR_GREY) },
    { BC_RED, GS_ID(GRAPHIC_SETTINGS_BAR_COLOR_RED) },
    { BC_SILVER, GS_ID(GRAPHIC_SETTINGS_BAR_COLOR_SILVER) },
    { BC_GREEN, GS_ID(GRAPHIC_SETTINGS_BAR_COLOR_GREEN) },
    { BC_GOLD2, GS_ID(GRAPHIC_SETTINGS_BAR_COLOR_GOLD2) },
    { BC_BLUE2, GS_ID(GRAPHIC_SETTINGS_BAR_COLOR_BLUE2) },
    { BC_PINK, GS_ID(GRAPHIC_SETTINGS_BAR_COLOR_PINK) },
    { BC_PURPLE, GS_ID(GRAPHIC_SETTINGS_BAR_COLOR_PURPLE) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_CameraModeEnumEntries[] = {
    { CAMERA_MODE_TR1, GS_ID(GRAPHIC_SETTINGS_CAMERA_MODE_TR1) },
    { CAMERA_MODE_TR2, GS_ID(GRAPHIC_SETTINGS_CAMERA_MODE_TR2) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_TextureFilterEnumEntries[] = {
    { GFX_TF_NN, GS_ID(GRAPHIC_SETTINGS_NEAREST_NEIGHBOR) },
    { GFX_TF_BILINEAR, GS_ID(GRAPHIC_SETTINGS_BILINEAR) },
    { -1, nullptr },
};

#if TR_VERSION == 1
const UI_SETTINGS_ENUM_ENTRY UI_Settings_RenderModeEnumEntries[] = {
    { GFX_RM_LEGACY, GS_ID(GRAPHIC_SETTINGS_RENDER_MODE_LEGACY) },
    { GFX_RM_FRAMEBUFFER, GS_ID(GRAPHIC_SETTINGS_RENDER_MODE_FBO) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_MenuStyleEnumEntries[] = {
    { UI_STYLE_PS1, GS_ID(GRAPHIC_SETTINGS_UI_STYLE_PS1) },
    { UI_STYLE_PC, GS_ID(GRAPHIC_SETTINGS_UI_STYLE_PC) },
    { -1, nullptr },
};
#elif TR_VERSION == 2
const UI_SETTINGS_ENUM_ENTRY UI_Settings_LightingContrastEnumEntries[] = {
    { LIGHTING_CONTRAST_LOW, GS_ID(GRAPHIC_SETTINGS_LIGHTING_CONTRAST_LOW) },
    { LIGHTING_CONTRAST_MEDIUM,
      GS_ID(GRAPHIC_SETTINGS_LIGHTING_CONTRAST_MEDIUM) },
    { LIGHTING_CONTRAST_HIGH, GS_ID(GRAPHIC_SETTINGS_LIGHTING_CONTRAST_HIGH) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_RenderModeEnumEntries[] = {
    { RM_SOFTWARE, GS_ID(GRAPHIC_SETTINGS_RENDER_MODE_SOFTWARE) },
    { RM_HARDWARE, GS_ID(GRAPHIC_SETTINGS_RENDER_MODE_HARDWARE) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_AspectModeEnumEntries[] = {
    { AM_4_3, GS_ID(GRAPHIC_SETTINGS_ASPECT_MODE_4_3) },
    { AM_16_9, GS_ID(GRAPHIC_SETTINGS_ASPECT_MODE_16_9) },
    { AM_ANY, GS_ID(GRAPHIC_SETTINGS_ASPECT_MODE_ANY) },
    { -1, nullptr },
};
#endif

const UI_SETTINGS_ENUM_ENTRY UI_Settings_ScreenshotFormatEnumEntries[] = {
    { SCREENSHOT_FORMAT_JPEG, GS_ID(GRAPHIC_SETTINGS_SCREENSHOT_FORMAT_JPG) },
    { SCREENSHOT_FORMAT_PNG, GS_ID(GRAPHIC_SETTINGS_SCREENSHOT_FORMAT_PNG) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_MusicLoadConditionEnumEntries[] = {
    { MUSIC_LOAD_NEVER, GS_ID(SOUND_SETTINGS_MUSIC_LOAD_CONDITION_NEVER) },
    { MUSIC_LOAD_NON_AMBIENT,
      GS_ID(SOUND_SETTINGS_MUSIC_LOAD_CONDITION_NON_AMBIENT) },
    { MUSIC_LOAD_ALWAYS, GS_ID(SOUND_SETTINGS_MUSIC_LOAD_CONDITION_ALWAYS) },
    { -1, nullptr },
};
