#include "game/ui/dialogs/setting_helpers/enums.h"

#include "config.h"
#include "game/lara/const.h"

#if TR_VERSION == 1
const UI_SETTINGS_ENUM_ENTRY UI_Settings_StatDetailModeEnumEntries[] = {
    { SDM_MINIMAL, GS_ID(ENUM_STAT_DETAIL_MODE_MINIMAL) },
    { SDM_DETAILED, GS_ID(ENUM_STAT_DETAIL_MODE_DETAILED) },
    { SDM_FULL, GS_ID(ENUM_STAT_DETAIL_MODE_FULL) },
    { -1, nullptr },
};
#endif

const UI_SETTINGS_ENUM_ENTRY UI_Settings_TargetModeEnumEntries[] = {
    { TLM_FULL, GS_ID(ENUM_TARGET_LOCK_MODE_FULL) },
    { TLM_SEMI, GS_ID(ENUM_TARGET_LOCK_MODE_SEMI) },
    { TLM_NONE, GS_ID(ENUM_TARGET_LOCK_MODE_NONE) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_LookModeEnumEntries[] = {
    { LOOK_MODE_RESTRICTED, GS_ID(ENUM_LOOK_MODE_RESTRICTED) },
    { LOOK_MODE_ENHANCED, GS_ID(ENUM_LOOK_MODE_ENHANCED) },
    { LOOK_MODE_UNRESTRICTED, GS_ID(ENUM_LOOK_MODE_UNRESTRICTED) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_QuickGunsModeEnumEntries[] = {
    { QUICK_GUNS_DRAW_ONLY, GS_ID(ENUM_QUICK_GUNS_MODE_DRAW_ONLY) },
    { QUICK_GUNS_DRAW_AND_HOLSTER,
      GS_ID(ENUM_QUICK_GUNS_MODE_DRAW_AND_HOLSTER) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_JumpLockModeEnumEntries[] = {
    { JUMP_LOCK_LEGACY, GS_ID(ENUM_JUMP_LOCK_LEGACY) },
    { JUMP_LOCK_TUNED, GS_ID(ENUM_JUMP_LOCK_TUNED) },
    { JUMP_LOCK_DISABLED, GS_ID(ENUM_JUMP_LOCK_DISABLED) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_WallGlitchEnumEntries[] = {
    { WALL_GLITCH_FIXED, GS_ID(ENUM_WALL_GLITCH_FIXED) },
    { WALL_GLITCH_TR1, GS_ID(ENUM_WALL_GLITCH_TR1) },
    { WALL_GLITCH_TR2, GS_ID(ENUM_WALL_GLITCH_TR2) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_HealthBarShowModeEnumEntries[] = {
    { BSM_DEFAULT, GS_ID(ENUM_BAR_MODE_DEFAULT) },
    { BSM_PS1, GS_ID(ENUM_BAR_MODE_PS1) },
    { BSM_FLASHING_OR_DEFAULT, GS_ID(ENUM_BAR_MODE_FLASHING_OR_DEFAULT) },
    { BSM_FLASHING_ONLY, GS_ID(ENUM_BAR_MODE_FLASHING_ONLY) },
    { BSM_ALWAYS, GS_ID(ENUM_BAR_MODE_ALWAYS) },
    { BSM_NEVER, GS_ID(ENUM_BAR_MODE_NEVER) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_AirBarShowModeEnumEntries[] = {
    { BSM_DEFAULT, GS_ID(ENUM_BAR_MODE_DEFAULT) },
    { BSM_PS1, GS_ID(ENUM_BAR_MODE_PS1) },
    { BSM_FLASHING_ONLY, GS_ID(ENUM_BAR_MODE_FLASHING_ONLY) },
    { BSM_NEVER, GS_ID(ENUM_BAR_MODE_NEVER) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_SprintBarShowModeEnumEntries[] = {
    { BSM_DEFAULT, GS_ID(ENUM_BAR_MODE_DEFAULT) },
    { BSM_NEVER, GS_ID(ENUM_BAR_MODE_NEVER) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_ExposureBarShowModeEnumEntries[] = {
    { BSM_DEFAULT, GS_ID(ENUM_BAR_MODE_DEFAULT) },
    { BSM_PS1, GS_ID(ENUM_BAR_MODE_PS1) },
    { BSM_FLASHING_ONLY, GS_ID(ENUM_BAR_MODE_FLASHING_ONLY) },
    { BSM_NEVER, GS_ID(ENUM_BAR_MODE_NEVER) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_EnemyHealthBarShowModeEnumEntries[] = {
    { BSM_ALWAYS, GS_ID(ENUM_BAR_MODE_ALWAYS) },
    { BSM_NEVER, GS_ID(ENUM_BAR_MODE_NEVER) },
    { BSM_BOSS_ONLY, GS_ID(ENUM_BAR_MODE_BOSS_ONLY) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_BarLocationEnumEntries[] = {
    { BL_TOP_LEFT, GS_ID(ENUM_BAR_LOCATION_TOP_LEFT) },
    { BL_TOP_CENTER, GS_ID(ENUM_BAR_LOCATION_TOP_CENTER) },
    { BL_TOP_RIGHT, GS_ID(ENUM_BAR_LOCATION_TOP_RIGHT) },
    { BL_BOTTOM_LEFT, GS_ID(ENUM_BAR_LOCATION_BOTTOM_LEFT) },
    { BL_BOTTOM_CENTER, GS_ID(ENUM_BAR_LOCATION_BOTTOM_CENTER) },
    { BL_BOTTOM_RIGHT, GS_ID(ENUM_BAR_LOCATION_BOTTOM_RIGHT) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_BarLookEnumEntries[] = {
    { BAR_LOOK_TR1, GS_ID(ENUM_BAR_LOOK_TR1) },
    { BAR_LOOK_TR23_PC, GS_ID(ENUM_BAR_LOOK_TR23_PC) },
    { BAR_LOOK_TR23_PS1, GS_ID(ENUM_BAR_LOOK_TR23_PS1) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_BackgroundStyleEnumEntries[] = {
    { BK_PATTERN_STATIC, GS_ID(ENUM_BK_PATTERN_STATIC) },
    { BK_PATTERN_WAVE, GS_ID(ENUM_BK_PATTERN_WAVE) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_BarColorEnumEntries[] = {
    { BC_GOLD, GS_ID(ENUM_BAR_COLOR_GOLD) },
    { BC_BLUE, GS_ID(ENUM_BAR_COLOR_BLUE) },
    { BC_GREY, GS_ID(ENUM_BAR_COLOR_GREY) },
    { BC_RED, GS_ID(ENUM_BAR_COLOR_RED) },
    { BC_SILVER, GS_ID(ENUM_BAR_COLOR_SILVER) },
    { BC_GREEN, GS_ID(ENUM_BAR_COLOR_GREEN) },
    { BC_GOLD2, GS_ID(ENUM_BAR_COLOR_GOLD2) },
    { BC_BLUE2, GS_ID(ENUM_BAR_COLOR_BLUE2) },
    { BC_PINK, GS_ID(ENUM_BAR_COLOR_PINK) },
    { BC_PURPLE, GS_ID(ENUM_BAR_COLOR_PURPLE) },
    { BC_GREEN2, GS_ID(ENUM_BAR_COLOR_GREEN2) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_CameraModeEnumEntries[] = {
    { CAMERA_MODE_TR1, GS_ID(ENUM_CAMERA_MODE_TR1) },
    { CAMERA_MODE_TR2, GS_ID(ENUM_CAMERA_MODE_TR2) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_TextureFilterEnumEntries[] = {
    { GFX_TF_POINT, GS_ID(ENUM_TEXTURE_FILTER_POINT) },
    { GFX_TF_BILINEAR, GS_ID(ENUM_TEXTURE_FILTER_BILINEAR) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_MenuStyleEnumEntries[] = {
    { UI_STYLE_PS1, GS_ID(ENUM_UI_STYLE_PS1) },
    { UI_STYLE_PC, GS_ID(ENUM_UI_STYLE_PC) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_LightingContrastEnumEntries[] = {
    { LIGHTING_CONTRAST_LOW, GS_ID(ENUM_LIGHTING_CONTRAST_LOW) },
    { LIGHTING_CONTRAST_MEDIUM, GS_ID(ENUM_LIGHTING_CONTRAST_MEDIUM) },
    { LIGHTING_CONTRAST_HIGH, GS_ID(ENUM_LIGHTING_CONTRAST_HIGH) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_SpriteLockModeEnumEntries[] = {
    { BILLBOARD_LOCK_NONE, GS_ID(ENUM_BILLBOARD_LOCK_NONE) },
    { BILLBOARD_LOCK_ROLL, GS_ID(ENUM_BILLBOARD_LOCK_ROLL) },
    { BILLBOARD_LOCK_ROLL_PITCH, GS_ID(ENUM_BILLBOARD_LOCK_ROLL_PITCH) },
    { BILLBOARD_LOCK_PERSPECTIVE, GS_ID(ENUM_BILLBOARD_LOCK_PERSPECTIVE) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_AspectModeEnumEntries[] = {
    { AM_4_3, GS_ID(ENUM_ASPECT_MODE_4_3) },
    { AM_16_9, GS_ID(ENUM_ASPECT_MODE_16_9) },
    { AM_16_10, GS_ID(ENUM_ASPECT_MODE_16_10) },
    { AM_ANY, GS_ID(ENUM_ASPECT_MODE_ANY) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_ScreenshotFormatEnumEntries[] = {
    { SCREENSHOT_FORMAT_JPEG, GS_ID(ENUM_SCREENSHOT_FORMAT_JPG) },
    { SCREENSHOT_FORMAT_PNG, GS_ID(ENUM_SCREENSHOT_FORMAT_PNG) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_MusicLoadConditionEnumEntries[] = {
    { MUSIC_LOAD_NEVER, GS_ID(ENUM_MUSIC_LOAD_CONDITION_NEVER) },
    { MUSIC_LOAD_NON_AMBIENT, GS_ID(ENUM_MUSIC_LOAD_CONDITION_NON_AMBIENT) },
    { MUSIC_LOAD_ALWAYS, GS_ID(ENUM_MUSIC_LOAD_CONDITION_ALWAYS) },
    { -1, nullptr },
};
