project(
  'TR1X',
  'c',
  default_options: [
    'c_std=c2x',
    'warning_level=3',
  ],
  meson_version: '>=1.3.0',
)

staticdeps = get_option('staticdeps')

trx = subproject('libtrx', default_options: {
  'tr_version': '1',
  'staticdeps': staticdeps,
})
c_compiler = meson.get_compiler('c')

fs = import('fs')
relative_dir = fs.relative_to(meson.current_source_dir(), meson.global_build_root())
build_opts = [
  # common options
  '-Wno-unused',
  '-Wno-unused-parameter',
  '-Wno-microsoft-anon-tag',
  '-Wno-gnu-binary-literal',
  '-Wno-gnu-empty-initializer',
  '-Wno-gnu-zero-variadic-macro-arguments',
  '-DMESON_BUILD',
  '-DGLEW_NO_GLU',
  '-DSDL_MAIN_HANDLED',
  '-fms-extensions',
  '-fno-omit-frame-pointer',
  # end of common options
  '-ffile-prefix-map=@0@/='.format(relative_dir),
  '-DTR_VERSION=1',
  '-DDEBUG=' + (get_option('buildtype') == 'debug' ? '1' : '0'),
] + trx.get_variable('defines')

add_project_arguments(build_opts, language: 'c')

# Always dynamically link on macOS
if host_machine.system() == 'darwin'
  staticdeps = false
endif

null_dep = dependency('', required: false)

dep_trx = trx.get_variable('dep_trx')
dep_avcodec = dependency('libavcodec', static: staticdeps)
dep_avformat = dependency('libavformat', static: staticdeps)
dep_avutil = dependency('libavutil', static: staticdeps)
dep_mathlibrary = c_compiler.find_library('m', static: staticdeps, required : false)
dep_swscale = dependency('libswscale', static: staticdeps)
dep_swresample = dependency('libswresample', static: staticdeps)
dep_sdl2 = dependency('SDL2', static: staticdeps)
dep_glew = dependency('glew', static: staticdeps)
dep_lua = dependency('lua', static: staticdeps)

# autogenerated files
resources = []
python3 = find_program('python3', required: true)
git = find_program('git', required: true)

init = custom_target(
  'fake_init',
  output: ['init.c'],
  command: [python3, meson.project_source_root() + '/../../tools/tr1/generate_init', '-o', meson.current_build_dir() / '@OUTPUT0@'],
  build_always_stale: true,
)

version_rc = custom_target(
  'fake_version',
  output: ['version.rc'],
  command: [python3, meson.project_source_root() + '/../../tools/tr1/generate_rcfile', '-o', '@OUTPUT0@'],
  build_always_stale: true,
)

icon_rc = custom_target(
  'fake_icon',
  output: ['icon.rc'],
  command: [python3, meson.project_source_root() + '/../../tools/tr1/generate_rcfile', '-o', '@OUTPUT0@'],
)

link_args = []

if host_machine.system() == 'windows'
  windows = import('windows')

  resources = [
    windows.compile_resources(version_rc),
    windows.compile_resources(icon_rc),
  ]

  link_args += ['-static']
endif

sources = [
  init,
  'game/creature.c',
  'game/cutscene.c',
  'game/demo.c',
  'game/effects.c',
  'game/game/game.c',
  'game/game/game_draw.c',
  'game/game_flow/common.c',
  'game/game_flow/sequencer_events.c',
  'game/game_flow/sequencer_misc.c',
  'game/game_string.c',
  'game/gun/gun_pistols.c',
  'game/gun/gun_rifle.c',
  'game/inventory.c',
  'game/inventory_ring/control.c',
  'game/inventory_ring/draw.c',
  'game/inventory_ring/vars.c',
  'game/item_actions.c',
  'game/item_actions/bubbles.c',
  'game/item_actions/chain_block.c',
  'game/item_actions/earthquake.c',
  'game/item_actions/explosion.c',
  'game/item_actions/finish_level.c',
  'game/item_actions/flicker.c',
  'game/item_actions/flipmap.c',
  'game/item_actions/flood.c',
  'game/item_actions/floor_shake.c',
  'game/item_actions/lara_effects.c',
  'game/item_actions/powerup.c',
  'game/item_actions/raising_block.c',
  'game/item_actions/sand.c',
  'game/item_actions/stairs2slope.c',
  'game/item_actions/turn_180.c',
  'game/lara/common.c',
  'game/los.c',
  'game/objects/common.c',
  'game/objects/creatures/cutscene_player.c',
  'game/objects/general/earthquake.c',
  'game/objects/general/pickup.c',
  'game/objects/general/save_crystal.c',
  'game/objects/general/switch.c',
  'game/objects/setup.c',
  'game/objects/traps/damocles_sword.c',
  'game/objects/traps/lightning_emitter.c',
  'game/option/option.c',
  'game/option/option_compass.c',
  'game/option/option_passport.c',
  'game/room_draw.c',
  'game/savegame/savegame.c',
  'game/savegame/savegame_bson.c',
  'game/savegame/savegame_legacy.c',
  'game/shell/common.c',
  'game/stats/common.c',
  'game/ui/dialogs/stats.c',
  'global/enum_map.c',
  'global/vars.c',
  resources,
]

dependencies = [
  dep_trx,
  dep_avcodec,
  dep_avformat,
  dep_avutil,
  dep_mathlibrary,
  dep_sdl2,
  dep_glew,
  dep_swresample,
  dep_swscale,
  dep_lua,
]

executable(
  'TR1X',
  sources,
  dependencies: dependencies,
  link_args: link_args,
  win_subsystem: 'windows',
  install: true,
)

if host_machine.system() == 'darwin'
  install_subdir('../../data/tr1/ship/cfg', install_dir : 'Contents/Resources')
  install_subdir('../../data/tr1/ship/data', install_dir : 'Contents/Resources')
  install_subdir('../../data/common/ship/cfg', install_dir : 'Contents/Resources')
  install_subdir('../../data/common/ship/shaders', install_dir : 'Contents/Resources')
  install_data('../../data/tr1/mac/icon.icns', install_dir : 'Contents/Resources')
  install_data('../../data/tr1/mac/Info.plist', install_dir : 'Contents')
  meson.add_install_script('../../tools/shared/mac/bundle_dylibs', '-a', 'TR1X')
endif
