require("trx.ui.widgets.base")
require("trx.ui.widgets.label")
require("trx.ui.widgets.image")
require("trx.ui.widgets.bar")
require("trx.ui.widgets.layout")
require("trx.ui.widgets.digits")
require("trx.ui.widgets.custom")
