#!/usr/bin/env python3
import re
from pathlib import Path


def sort_imports(path: Path) -> None:
    source = path.read_text()

    def cb(match):
        # print("<>" + match.group(0) + "</>")
        return (
            "\n".join(sorted(set(match.group("includes").splitlines()))) + "\n"
        )

    source = re.sub(
        "(?P<includes>(^#include [^\n]+\n)+)(?=\n)",
        cb,
        source,
        flags=re.M,
    )
    if source != path.read_text():
        path.write_text(source)


for path in sorted(Path().glob("**/*.[ch]")):
    sort_imports(path)
