#pragma once

typedef enum {
    AM_4_3,
    AM_16_9,
    AM_16_10,
    AM_ANY,
} ASPECT_MODE;

typedef enum {
    BK_TRANSPARENT,
    BK_PATTERN_STATIC,
    BK_PATTERN_WAVE,
    BK_IMAGE,
} BACKGROUND_TYPE;

typedef enum {
    BL_TOP_LEFT,
    BL_TOP_CENTER,
    BL_TOP_RIGHT,
    BL_BOTTOM_LEFT,
    BL_BOTTOM_CENTER,
    BL_BOTTOM_RIGHT,
    BL_CUSTOM,
} BAR_LOCATION;

typedef enum {
    BSM_DEFAULT,
    BSM_FLASHING_OR_DEFAULT,
    BSM_FLASHING_ONLY,
    BSM_ALWAYS,
    BSM_NEVER,
    BSM_PS1,
    BSM_BOSS_ONLY,
} BAR_SHOW_MODE;

typedef enum {
    BC_GOLD,
    BC_BLUE,
    BC_GREY,
    BC_RED,
    BC_SILVER,
    BC_GREEN,
    BC_GOLD2,
    BC_BLUE2,
    BC_PINK,
    BC_PURPLE,
    BC_GREEN2,
    BC_NUMBER_OF,
} BAR_COLOR;

typedef enum {
    BAR_LOOK_TR1,
    BAR_LOOK_TR23_PC,
    BAR_LOOK_TR23_PS1,
} BAR_LOOK;

typedef enum {
    MUSIC_LOAD_NEVER,
    MUSIC_LOAD_NON_AMBIENT,
    MUSIC_LOAD_ALWAYS,
} MUSIC_LOAD_CONDITION;

typedef enum {
    UI_STYLE_PS1,
    UI_STYLE_PC,
} UI_STYLE;

typedef enum {
    CAMERA_MODE_TR1,
    CAMERA_MODE_TR2,
    CAMERA_MODE_NUMBER_OF,
} CAMERA_MODE;

typedef enum {
    WALL_GLITCH_FIXED,
    WALL_GLITCH_TR1,
    WALL_GLITCH_TR2,
} WALL_GLITCH_MODE;

typedef enum {
    JUMP_LOCK_LEGACY,
    JUMP_LOCK_TUNED,
    JUMP_LOCK_DISABLED,
    JUMP_LOCK_NUMBER_OF,
} JUMP_LOCK_MODE;

typedef enum {
    LOOK_MODE_RESTRICTED,
    LOOK_MODE_ENHANCED,
    LOOK_MODE_UNRESTRICTED,
} LOOK_MODE;

typedef enum {
    QUICK_GUNS_DRAW_ONLY,
    QUICK_GUNS_DRAW_AND_HOLSTER,
} QUICK_GUNS_MODE;

typedef enum {
    LIGHTING_CONTRAST_LOW,
    LIGHTING_CONTRAST_MEDIUM,
    LIGHTING_CONTRAST_HIGH,
    LIGHTING_CONTRAST_NUMBER_OF,
} LIGHTING_CONTRAST;

typedef enum {
    BILLBOARD_LOCK_NONE,
    BILLBOARD_LOCK_ROLL,
    BILLBOARD_LOCK_ROLL_PITCH,
    BILLBOARD_LOCK_PERSPECTIVE,
    BILLBOARD_LOCK_NUMBER_OF,
} BILLBOARD_LOCK_MODE;

typedef enum {
    TLM_FULL,
    TLM_SEMI,
    TLM_NONE,
} TARGET_LOCK_MODE;

#if TR_VERSION == 1
typedef enum {
    SDM_MINIMAL,
    SDM_DETAILED,
    SDM_FULL,
} STAT_DETAIL_MODE;
#endif
