#!/usr/bin/env python3
import argparse
import re
from pathlib import Path

from shared.versioning import generate_version

TEMPLATE = """
const char *g_TRXVersion = "TR{game_version}X {version}";
""".lstrip()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("-o", "--output", type=Path)
    return parser.parse_args()


def get_init_c(game_version: int) -> str:
    return TEMPLATE.format(
        game_version=game_version, version=generate_version(game_version)
    )


def update_init_c(game_version: int, output_path: Path) -> None:
    new_text = get_init_c(game_version=game_version)
    if not output_path.exists() or output_path.read_text() != new_text:
        output_path.write_text(new_text)


def main() -> None:
    args = parse_args()
    game_version = int(re.search(r"tr(\d)_", str(args.output)).group(1))
    if args.output:
        update_init_c(game_version=game_version, output_path=args.output)
    else:
        print(get_init_c(), end="")


if __name__ == "__main__":
    main()
