#!/usr/bin/env python3
import argparse

from shared.versioning import generate_version


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    print(generate_version(), end="")


if __name__ == "__main__":
    main()
