#!/usr/bin/env python3
import argparse

from shared.changelog import Changelog, get_current_version_changelog
from shared.git import Git
from shared.paths import PROJECT_PATHS
from shared.versioning import generate_version


def output_changelog(
    changelog: Changelog, commit_hash: str | None = None
) -> None:
    print(f"**{changelog.release_name}** – ", end="")
    if changelog.release_date:
        print(f"{changelog.release_date:%Y-%m-%d}", end=" - ")
    print(f"[Diff]({changelog.diff_url})", end=" · ")
    print(f"[History]({changelog.commits_url})")
    print()
    print("### Changes:")
    print(changelog.body)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("version", choices=["1", "2", "all"])
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    commit_hash = Git().get_current_commit_hash()

    if args.version == "all":
        print(f"**Commit: {commit_hash}**  ")
        print()
        for version, project_paths in PROJECT_PATHS.items():
            commit_tag = generate_version(version)
            changelog = get_current_version_changelog(
                project_paths.changelog_path
            )
            print(f"### TR{version}X changes")
            print()
            output_changelog(changelog)
    else:
        project_paths = PROJECT_PATHS.get(int(args.version))
        commit_tag = generate_version(int(args.version))
        changelog = get_current_version_changelog(project_paths.changelog_path)
        output_changelog(changelog, commit_hash=commit_hash)


if __name__ == "__main__":
    main()
