#!/usr/bin/env python3
import argparse

from shared.versioning import generate_version


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    return parser.parse_args()


def get_release_name() -> str:
    return f"TRX {generate_version()}"


def main() -> None:
    args = parse_args()
    print(get_release_name())


if __name__ == "__main__":
    main()
