#!/usr/bin/env python3
import argparse

from shared.versioning import generate_package_name, generate_version


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("-g", "--game", type=int)
    parser.add_argument("-p", "--platform", required=True)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    print(
        generate_package_name(
            engine_version=generate_version(),
            platform=args.platform,
            game_version=args.game,
        )
    )


if __name__ == "__main__":
    main()
