#!/usr/bin/env python3
from libtrx.cli.sort_imports import run_script
from tr1x.paths import TR1X_REPO_DIR, TR1X_SRC_DIR

run_script(
    root_dir=TR1X_SRC_DIR,
    include_dirs=[
        TR1X_SRC_DIR,
        TR1X_REPO_DIR / "build/linux",
        TR1X_REPO_DIR / "build/windows",
    ],
    system_include_dirs=[TR1X_REPO_DIR / "subprojects/libtrx/include"],
    own_include_map={
        "game/game/game.c": "game/game.h",
        "game/game/game_cutscene.c": "game/game.h",
        "game/game/game_demo.c": "game/game.h",
        "game/game/game_draw.c": "game/game.h",
        "game/game/game_pause.c": "game/game.h",
        "game/gun/gun.c": "game/gun.h",
        "game/inventry.c": "game/inv.h",
        "game/invfunc.c": "game/inv.h",
        "game/invvars.c": "game/inv.h",
        "game/lara/lara.c": "game/lara.h",
        "game/option/option.c": "game/option.h",
        "game/savegame/savegame.c": "game/savegame.h",
        "specific/s_audio_sample.c": "specific/s_audio.h",
        "specific/s_audio_stream.c": "specific/s_audio.h",
        "specific/s_shell.c": "specific/s_shell.h",
    },
    fix_map={"libavcodec/version_major.h": "libavcodec/version.h"},
    forced_order=[],
)
