#include <trx/game/ui/dialogs/setting_helpers/enums.h>

#include <trx/config.h>
#include <trx/game/lara/const.h>

const UI_SETTINGS_ENUM_ENTRY UI_Settings_StatDetailModeEnumEntries[] = {
    { SDM_MINIMAL, GS_ID(ENUM_STAT_DETAIL_MODE_MINIMAL) },
    { SDM_DETAILED, GS_ID(ENUM_STAT_DETAIL_MODE_DETAILED) },
    { SDM_FULL, GS_ID(ENUM_STAT_DETAIL_MODE_FULL) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_TargetModeEnumEntries[] = {
    { TLM_FULL, GS_ID(ENUM_TARGET_LOCK_MODE_FULL) },
    { TLM_SEMI, GS_ID(ENUM_TARGET_LOCK_MODE_SEMI) },
    { TLM_NONE, GS_ID(ENUM_TARGET_LOCK_MODE_NONE) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_LookModeEnumEntries[] = {
    { LOOK_MODE_RESTRICTED, GS_ID(ENUM_LOOK_MODE_RESTRICTED) },
    { LOOK_MODE_ENHANCED, GS_ID(ENUM_LOOK_MODE_ENHANCED) },
    { LOOK_MODE_UNRESTRICTED, GS_ID(ENUM_LOOK_MODE_UNRESTRICTED) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_QuickGunsModeEnumEntries[] = {
    { QUICK_GUNS_DRAW_ONLY, GS_ID(ENUM_QUICK_GUNS_MODE_DRAW_ONLY) },
    { QUICK_GUNS_DRAW_AND_HOLSTER,
      GS_ID(ENUM_QUICK_GUNS_MODE_DRAW_AND_HOLSTER) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_JumpLockModeEnumEntries[] = {
    { JUMP_LOCK_LEGACY, GS_ID(ENUM_JUMP_LOCK_LEGACY) },
    { JUMP_LOCK_TUNED, GS_ID(ENUM_JUMP_LOCK_TUNED) },
    { JUMP_LOCK_DISABLED, GS_ID(ENUM_JUMP_LOCK_DISABLED) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_WallGlitchEnumEntries[] = {
    { WALL_GLITCH_FIXED, GS_ID(ENUM_WALL_GLITCH_FIXED) },
    { WALL_GLITCH_TR1, GS_ID(ENUM_WALL_GLITCH_TR1) },
    { WALL_GLITCH_TR2, GS_ID(ENUM_WALL_GLITCH_TR2) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_EnemyHealthBarShowModeEnumEntries[] = {
    { BSM_NEVER, GS_ID(ENUM_BAR_MODE_NEVER) },
    { BSM_BOSS_ONLY, GS_ID(ENUM_BAR_MODE_BOSS_ONLY) },
    { BSM_ALWAYS, GS_ID(ENUM_BAR_MODE_ALWAYS) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_BarLocationEnumEntries[] = {
    { BL_TOP_LEFT, GS_ID(ENUM_BAR_LOCATION_TOP_LEFT) },
    { BL_TOP_CENTER, GS_ID(ENUM_BAR_LOCATION_TOP_CENTER) },
    { BL_TOP_RIGHT, GS_ID(ENUM_BAR_LOCATION_TOP_RIGHT) },
    { BL_BOTTOM_LEFT, GS_ID(ENUM_BAR_LOCATION_BOTTOM_LEFT) },
    { BL_BOTTOM_CENTER, GS_ID(ENUM_BAR_LOCATION_BOTTOM_CENTER) },
    { BL_BOTTOM_RIGHT, GS_ID(ENUM_BAR_LOCATION_BOTTOM_RIGHT) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_BackgroundStyleEnumEntries[] = {
    { BK_TRANSPARENT_MEDIUM, GS_ID(ENUM_BK_TRANSPARENT_MEDIUM) },
    { BK_TRANSPARENT_DARK, GS_ID(ENUM_BK_TRANSPARENT_DARK) },
    { BK_PATTERN_STATIC, GS_ID(ENUM_BK_PATTERN_STATIC) },
    { BK_PATTERN_WAVE, GS_ID(ENUM_BK_PATTERN_WAVE) },
    { BK_MONOCHROME, GS_ID(ENUM_BK_MONOCHROME) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_CameraModeEnumEntries[] = {
    { CAMERA_MODE_TR1, GS_ID(ENUM_CAMERA_MODE_TR1) },
    { CAMERA_MODE_TR2, GS_ID(ENUM_CAMERA_MODE_TR2) },
    { CAMERA_MODE_TR3, GS_ID(ENUM_CAMERA_MODE_TR3) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_TextureFilterEnumEntries[] = {
    { TRX_GL_TF_POINT, GS_ID(ENUM_TEXTURE_FILTER_POINT) },
    { TRX_GL_TF_BILINEAR, GS_ID(ENUM_TEXTURE_FILTER_BILINEAR) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_MenuStyleEnumEntries[] = {
    { UI_STYLE_PS1, GS_ID(ENUM_UI_STYLE_PS1) },
    { UI_STYLE_PC, GS_ID(ENUM_UI_STYLE_PC) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_LightingContrastEnumEntries[] = {
    { LIGHTING_CONTRAST_LOW, GS_ID(ENUM_LIGHTING_CONTRAST_LOW) },
    { LIGHTING_CONTRAST_MEDIUM, GS_ID(ENUM_LIGHTING_CONTRAST_MEDIUM) },
    { LIGHTING_CONTRAST_HIGH, GS_ID(ENUM_LIGHTING_CONTRAST_HIGH) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_SpriteLockModeEnumEntries[] = {
    { BILLBOARD_LOCK_NONE, GS_ID(ENUM_BILLBOARD_LOCK_NONE) },
    { BILLBOARD_LOCK_ROLL, GS_ID(ENUM_BILLBOARD_LOCK_ROLL) },
    { BILLBOARD_LOCK_ROLL_PITCH, GS_ID(ENUM_BILLBOARD_LOCK_ROLL_PITCH) },
    { BILLBOARD_LOCK_PERSPECTIVE, GS_ID(ENUM_BILLBOARD_LOCK_PERSPECTIVE) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_AspectModeEnumEntries[] = {
    { AM_4_3, GS_ID(ENUM_ASPECT_MODE_4_3) },
    { AM_16_9, GS_ID(ENUM_ASPECT_MODE_16_9) },
    { AM_16_10, GS_ID(ENUM_ASPECT_MODE_16_10) },
    { AM_ANY, GS_ID(ENUM_ASPECT_MODE_ANY) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_ScreenshotFormatEnumEntries[] = {
    { SCREENSHOT_FORMAT_JPEG, GS_ID(ENUM_SCREENSHOT_FORMAT_JPG) },
    { SCREENSHOT_FORMAT_PNG, GS_ID(ENUM_SCREENSHOT_FORMAT_PNG) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_AllyHostilityPolicyEnumEntries[] = {
    { ALLY_HOSTILITY_POLICY_INDIVIDUAL,
      GS_ID(ENUM_ALLY_HOSTILITY_POLICY_INDIVIDUAL) },
    { ALLY_HOSTILITY_POLICY_SHARED, GS_ID(ENUM_ALLY_HOSTILITY_POLICY_SHARED) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_ProjectileAreaDamageEnumEntries[] = {
    { PROJECTILE_AREA_DAMAGE_SINGLE_SWEEP,
      GS_ID(ENUM_PROJECTILE_AREA_DAMAGE_SINGLE_SWEEP) },
    { PROJECTILE_AREA_DAMAGE_MULTI_SWEEP,
      GS_ID(ENUM_PROJECTILE_AREA_DAMAGE_MUTLI_SWEEP) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_LoadingScreensModeEnumEntries[] = {
    { LOADING_SCREENS_DISABLED, GS_ID(ENUM_LOADING_SCREENS_DISABLED) },
    { LOADING_SCREENS_ALWAYS, GS_ID(ENUM_LOADING_SCREENS_ALWAYS) },
    { LOADING_SCREENS_NEW_GAMES, GS_ID(ENUM_LOADING_SCREENS_NEW_GAMES) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_MusicLoadConditionEnumEntries[] = {
    { MUSIC_LOAD_NEVER, GS_ID(ENUM_MUSIC_LOAD_CONDITION_NEVER) },
    { MUSIC_LOAD_NON_AMBIENT, GS_ID(ENUM_MUSIC_LOAD_CONDITION_NON_AMBIENT) },
    { MUSIC_LOAD_ALWAYS, GS_ID(ENUM_MUSIC_LOAD_CONDITION_ALWAYS) },
    { -1, nullptr },
};

const UI_SETTINGS_ENUM_ENTRY UI_Settings_ShadowTypeEnumEntries[] = {
    { SHADOW_TYPE_OCTAGON, GS_ID(ENUM_SHADOW_TYPE_OCTAGON) },
    { SHADOW_TYPE_CIRCLE, GS_ID(ENUM_SHADOW_TYPE_CIRCLE) },
    { SHADOW_TYPE_SPRITE, GS_ID(ENUM_SHADOW_TYPE_SPRITE) },
    { -1, nullptr },
};
