#include "init.h"

#include "game/gameflow.h"
#include "global/vars.h"

// THIS IS AN AUTOGENERATED FILE.
// To generate it, run scripts/generate_init.

#ifndef VERSION
    #define VERSION "T1M (unknown version)"
#endif

const char *g_T1MVersion = VERSION;

void T1MInit()
{
    g_GameFlow.strings[GS_HEADING_INVENTORY] = "INVENTORY";
    g_GameFlow.strings[GS_HEADING_GAME_OVER] = "GAME OVER";
    g_GameFlow.strings[GS_HEADING_OPTION] = "OPTION";
    g_GameFlow.strings[GS_HEADING_ITEMS] = "ITEMS";
    g_GameFlow.strings[GS_PASSPORT_SELECT_LEVEL] = "Select Level";
    g_GameFlow.strings[GS_PASSPORT_SELECT_MODE] = "Select Mode";
    g_GameFlow.strings[GS_PASSPORT_MODE_NEW_GAME] = "New Game";
    g_GameFlow.strings[GS_PASSPORT_MODE_NEW_GAME_PLUS] = "New Game+";
    g_GameFlow.strings[GS_PASSPORT_MODE_NEW_GAME_JP] = "Japanese NG";
    g_GameFlow.strings[GS_PASSPORT_MODE_NEW_GAME_JP_PLUS] = "Japanese NG+";
    g_GameFlow.strings[GS_PASSPORT_NEW_GAME] = "New Game";
    g_GameFlow.strings[GS_PASSPORT_LOAD_GAME] = "Load Game";
    g_GameFlow.strings[GS_PASSPORT_SAVE_GAME] = "Save Game";
    g_GameFlow.strings[GS_PASSPORT_EXIT_GAME] = "Exit Game";
    g_GameFlow.strings[GS_PASSPORT_EXIT_TO_TITLE] = "Exit to Title";
    g_GameFlow.strings[GS_DETAIL_SELECT_DETAIL] = "Select Detail";
    g_GameFlow.strings[GS_DETAIL_LEVEL_HIGH] = "High";
    g_GameFlow.strings[GS_DETAIL_LEVEL_MEDIUM] = "Medium";
    g_GameFlow.strings[GS_DETAIL_LEVEL_LOW] = "Low";
    g_GameFlow.strings[GS_DETAIL_PERSPECTIVE_FMT] = "Perspective     %s";
    g_GameFlow.strings[GS_DETAIL_BILINEAR_FMT] = "Bilinear        %s";
    g_GameFlow.strings[GS_DETAIL_BRIGHTNESS_FMT] = "Brightness      %.1f";
    g_GameFlow.strings[GS_DETAIL_UI_TEXT_SCALE_FMT] = "UI text scale   %.1f";
    g_GameFlow.strings[GS_DETAIL_UI_BAR_SCALE_FMT] = "UI bar scale    %.1f";
    g_GameFlow.strings[GS_DETAIL_VIDEO_MODE_FMT] = "Game Video Mode %s";
    g_GameFlow.strings[GS_SOUND_SET_VOLUMES] = "Set Volumes";
    g_GameFlow.strings[GS_CONTROL_DEFAULT_KEYS] = "Default Keys";
    g_GameFlow.strings[GS_CONTROL_USER_KEYS] = "User Keys";
    g_GameFlow.strings[GS_KEYMAP_RUN] = "Run";
    g_GameFlow.strings[GS_KEYMAP_BACK] = "Back";
    g_GameFlow.strings[GS_KEYMAP_LEFT] = "Left";
    g_GameFlow.strings[GS_KEYMAP_RIGHT] = "Right";
    g_GameFlow.strings[GS_KEYMAP_STEP_LEFT] = "Step Left";
    g_GameFlow.strings[GS_KEYMAP_STEP_RIGHT] = "Step Right";
    g_GameFlow.strings[GS_KEYMAP_WALK] = "Walk";
    g_GameFlow.strings[GS_KEYMAP_JUMP] = "Jump";
    g_GameFlow.strings[GS_KEYMAP_ACTION] = "Action";
    g_GameFlow.strings[GS_KEYMAP_DRAW_WEAPON] = "Draw Weapon";
    g_GameFlow.strings[GS_KEYMAP_LOOK] = "Look";
    g_GameFlow.strings[GS_KEYMAP_ROLL] = "Roll";
    g_GameFlow.strings[GS_KEYMAP_INVENTORY] = "Inventory";
    g_GameFlow.strings[GS_KEYMAP_PAUSE] = "Pause";
    g_GameFlow.strings[GS_KEYMAP_FLY_CHEAT] = "Fly cheat";
    g_GameFlow.strings[GS_KEYMAP_ITEM_CHEAT] = "Item cheat";
    g_GameFlow.strings[GS_KEYMAP_LEVEL_SKIP_CHEAT] = "Level skip";
    g_GameFlow.strings[GS_KEYMAP_CAMERA_UP] = "Camera Up";
    g_GameFlow.strings[GS_KEYMAP_CAMERA_DOWN] = "Camera Down";
    g_GameFlow.strings[GS_KEYMAP_CAMERA_LEFT] = "Camera Left";
    g_GameFlow.strings[GS_KEYMAP_CAMERA_RIGHT] = "Camera Right";
    g_GameFlow.strings[GS_KEYMAP_CAMERA_RESET] = "Reset Camera";
    g_GameFlow.strings[GS_STATS_TIME_TAKEN_FMT] = "TIME TAKEN %s";
    g_GameFlow.strings[GS_STATS_SECRETS_FMT] = "SECRETS %d OF %d";
    g_GameFlow.strings[GS_STATS_PICKUPS_FMT] = "PICKUPS %d";
    g_GameFlow.strings[GS_STATS_KILLS_FMT] = "KILLS %d";
    g_GameFlow.strings[GS_PAUSE_PAUSED] = "Paused";
    g_GameFlow.strings[GS_PAUSE_EXIT_TO_TITLE] = "Exit to title?";
    g_GameFlow.strings[GS_PAUSE_CONTINUE] = "Continue";
    g_GameFlow.strings[GS_PAUSE_QUIT] = "Quit";
    g_GameFlow.strings[GS_PAUSE_ARE_YOU_SURE] = "Are you sure?";
    g_GameFlow.strings[GS_PAUSE_YES] = "Yes";
    g_GameFlow.strings[GS_PAUSE_NO] = "No";
    g_GameFlow.strings[GS_MISC_ON] = "On";
    g_GameFlow.strings[GS_MISC_OFF] = "Off";
    g_GameFlow.strings[GS_MISC_EMPTY_SLOT_FMT] = "- EMPTY SLOT %d -";
    g_GameFlow.strings[GS_MISC_DEMO_MODE] = "Demo Mode";
    g_GameFlow.strings[GS_INV_ITEM_MEDI] = "Small Medi Pack";
    g_GameFlow.strings[GS_INV_ITEM_BIG_MEDI] = "Large Medi Pack";
    g_GameFlow.strings[GS_INV_ITEM_PUZZLE1] = "Puzzle";
    g_GameFlow.strings[GS_INV_ITEM_PUZZLE2] = "Puzzle";
    g_GameFlow.strings[GS_INV_ITEM_PUZZLE3] = "Puzzle";
    g_GameFlow.strings[GS_INV_ITEM_PUZZLE4] = "Puzzle";
    g_GameFlow.strings[GS_INV_ITEM_KEY1] = "Key";
    g_GameFlow.strings[GS_INV_ITEM_KEY2] = "Key";
    g_GameFlow.strings[GS_INV_ITEM_KEY3] = "Key";
    g_GameFlow.strings[GS_INV_ITEM_KEY4] = "Key";
    g_GameFlow.strings[GS_INV_ITEM_PICKUP1] = "Pickup";
    g_GameFlow.strings[GS_INV_ITEM_PICKUP2] = "Pickup";
    g_GameFlow.strings[GS_INV_ITEM_LEADBAR] = "Lead Bar";
    g_GameFlow.strings[GS_INV_ITEM_SCION] = "Scion";
    g_GameFlow.strings[GS_INV_ITEM_PISTOLS] = "Pistols";
    g_GameFlow.strings[GS_INV_ITEM_SHOTGUN] = "Shotgun";
    g_GameFlow.strings[GS_INV_ITEM_MAGNUM] = "Magnums";
    g_GameFlow.strings[GS_INV_ITEM_UZI] = "Uzis";
    g_GameFlow.strings[GS_INV_ITEM_GRENADE] = "Grenade";
    g_GameFlow.strings[GS_INV_ITEM_PISTOL_AMMO] = "Pistol Clips";
    g_GameFlow.strings[GS_INV_ITEM_SHOTGUN_AMMO] = "Shotgun Shells";
    g_GameFlow.strings[GS_INV_ITEM_MAGNUM_AMMO] = "Magnum Clips";
    g_GameFlow.strings[GS_INV_ITEM_UZI_AMMO] = "Uzi Clips";
    g_GameFlow.strings[GS_INV_ITEM_COMPASS] = "Compass";
    g_GameFlow.strings[GS_INV_ITEM_GAME] = "Game";
    g_GameFlow.strings[GS_INV_ITEM_DETAILS] = "Detail Levels";
    g_GameFlow.strings[GS_INV_ITEM_SOUND] = "Sound";
    g_GameFlow.strings[GS_INV_ITEM_CONTROLS] = "Controls";
    g_GameFlow.strings[GS_INV_ITEM_LARAS_HOME] = "Lara's Home";
}
