#pragma once

#define SHOTGUN_PELLET_SCATTER (DEG_1 * 20) // = 3640

#define GUN_AMMO_CLIP 16
#define GUN_AMMO_QTY (GUN_AMMO_CLIP * 2) // = 32

#define SHOTGUN_SHELL_COUNT 2
#define SHOTGUN_AMMO_CLIP 6
#define SHOTGUN_AMMO_QTY (SHOTGUN_AMMO_CLIP * SHOTGUN_SHELL_COUNT) // = 12

#define FLARE_AMMO_QTY 6
#define FLARE_AMMO_JAPANESE_QTY 8

#define MAGNUM_AMMO_CLIP 25
#define MAGNUM_AMMO_QTY (MAGNUM_AMMO_CLIP * 2) // = 50

#define AUTOS_AMMO_CLIP 20
#define AUTOS_AMMO_QTY (AUTOS_AMMO_CLIP * 2) // = 40

#define DESERT_EAGLE_AMMO_CLIP 10
#define DESERT_EAGLE_AMMO_QTY DESERT_EAGLE_AMMO_CLIP // = 10

#define UZI_AMMO_CLIP (g_TRVersion == 1 ? 50 : 40)
#define UZI_AMMO_QTY (UZI_AMMO_CLIP * 2) // = 100 (TR1), 80 (TR2)

#define M16_AMMO_CLIP 40
#define M16_AMMO_QTY M16_AMMO_CLIP // = 40

#define MP5_AMMO_CLIP 60
#define MP5_AMMO_QTY MP5_AMMO_CLIP // = 60

#define HARPOON_AMMO_CLIP 3
#define HARPOON_AMMO_QTY HARPOON_AMMO_CLIP // = 3
#define HARPOON_BOLT_SPEED 150

#define GRENADE_AMMO_CLIP 1
#define GRENADE_AMMO_QTY (GRENADE_AMMO_CLIP * 2) // = 2
#define GRENADE_SPEED 200

#define ROCKET_AMMO_CLIP 1
#define ROCKET_AMMO_QTY ROCKET_AMMO_CLIP // = 1
