name: Build Docker toolchain

on:
  - workflow_dispatch

jobs:
  publish_docker_image:
    name: Build Docker toolchain
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: win
          - platform: linux
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7 # v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Install dependencies
        uses: taiki-e/install-action@6d97d0d47ea06f0bb4e81bc7911476e7cc61b312 # just

      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          submodules: 'true'

      - name: Build Docker image (${{ matrix.platform }})
        run: |
          just image-${{ matrix.platform }}
          just push-image-${{ matrix.platform }}
