name: Build TRX and the installer

on:
  workflow_call:
    inputs:
      platform:
        type: string
        description: "Platform to build for"
        required: true
      target:
        type: string
        description: "Target to build for"
        required: true
      zip:
        type: boolean
        description: "Pack the artifacts into zip"
        required: true
    outputs:
      trx_asset:
        description: "Uploaded artifact name"
        value: ${{ jobs.build.outputs.trx_asset }}

jobs:
  build:
    name: Build release assets
    runs-on: ubuntu-latest
    outputs:
      trx_asset: ${{ steps.vars.outputs.trx_asset }}

    steps:
      - name: Install dependencies
        uses: taiki-e/install-action@just

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - id: vars
        name: Prepare variables
        run: |
          echo "version=$(just output-current-version)" >> $GITHUB_OUTPUT
          echo "trx_dir=build/artifacts/trx/" >> $GITHUB_OUTPUT
          echo "trx_asset=$(just output-package-name --platform ${{ inputs.platform }})" >> $GITHUB_OUTPUT

      - name: Download large assets
        if: ${{ inputs.target == 'release' }}
        run: just download-assets

      - name: Restore ccache
        if: ${{ inputs.platform == 'linux' || inputs.platform == 'win' }}
        uses: actions/cache@v4
        with:
          path: .cache/ccache
          key: ccache-v1-${{ runner.os }}-${{ inputs.platform }}-${{ inputs.target }}-${{ hashFiles('justfile', 'tools/shared/docker/game-linux/Dockerfile', 'tools/shared/docker/game-win/Dockerfile', 'tools/shared/docker/game-win/meson_linux_mingw32.txt') }}
          restore-keys: |
            ccache-v1-${{ runner.os }}-${{ inputs.platform }}-${{ inputs.target }}-
            ccache-v1-${{ runner.os }}-${{ inputs.platform }}-

      - name: Package asset (${{ inputs.platform }})
        env:
          CCACHE_DIR: /app/.cache/ccache/${{ inputs.platform }}-${{ inputs.target }}
          CCACHE_BASEDIR: /app
          CCACHE_COMPILERCHECK: content
          CCACHE_MAXSIZE: 1G
        run: |
          mkdir -p ".cache/ccache/${{ inputs.platform }}-${{ inputs.target }}"
          if [ "${{ inputs.zip }}" = "1" ] || [ "${{ inputs.zip }}" = "true" ]; then
            just trx-package-${{ inputs.platform }} "${{ inputs.target }}" -o "${{ steps.vars.outputs.trx_dir }}"
          else
            just trx-package-${{ inputs.platform }} "${{ inputs.target }}" -o "${{ steps.vars.outputs.trx_dir }}" --no-zip
          fi

      - name: Upload artifacts (combined)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.vars.outputs.trx_asset }}
          path: ${{ steps.vars.outputs.trx_dir }}
          compression-level: 0
