name: Build TR2X

on:
  workflow_call:
    inputs:
      target:
        type: string
        description: "Target to build for"
        required: true

jobs:
  build:
    name: Build release assets
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: win
            just_target: tr2-package-win-all ${{ inputs.target }}

    steps:
      - name: Install dependencies
        uses: taiki-e/install-action@just

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - id: vars
        name: Prepare variables
        run: echo "version=$(just output-current-version 2)" >> $GITHUB_OUTPUT

      - name: Package asset (${{ matrix.platform }})
        run: just ${{ matrix.just_target }}

      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: TR2X-${{ steps.vars.outputs.version }}-${{ matrix.platform }}
          path: |
            *.zip
            *.exe
