name: Create a test build

permissions:
  contents: write

on:
  pull_request:
  push:
    branches:
      - '!stable'
      - '!develop'

jobs:
  package_tr1_multiplatform:
    name: Build TR1
    uses: ./.github/workflows/job_build_tr1.yml
    secrets: inherit

  package_tr1_mac:
    name: Build TR1
    if: vars.MACOS_ENABLE == 'true'
    uses: ./.github/workflows/job_build_tr1_macos.yml
    with:
      let_mac_fail: true
    secrets: inherit

  package_tr2_multiplatform:
    name: Build TR2
    uses: ./.github/workflows/job_build_tr2.yml
    secrets: inherit
