name: Create a test build

permissions:
  contents: write

on:
  pull_request:
  push:
    branches:
      - '!stable'
      - '!develop'

jobs:
  package_tr1_linux:
    name: TR1 (Linux)
    uses: ./.github/workflows/job_build_tr1.yml
    with:
      platform: linux
      target: debug
    secrets: inherit

  package_tr1_win:
    name: TR1 (Windows)
    uses: ./.github/workflows/job_build_tr1.yml
    with:
      platform: win
      target: debug
    secrets: inherit

  package_tr1_mac:
    name: TR1 (Mac)
    if: vars.MACOS_ENABLE == 'true'
    uses: ./.github/workflows/job_build_tr1_macos.yml
    with:
      target: debug
      let_mac_fail: true
    secrets: inherit

  package_tr2_linux:
    name: TR2 (Linux)
    uses: ./.github/workflows/job_build_tr2.yml
    with:
      platform: linux
      target: debug
    secrets: inherit

  package_tr2_win:
    name: TR2 (Windows)
    uses: ./.github/workflows/job_build_tr2.yml
    with:
      platform: win
      target: debug
    secrets: inherit

  package_tr2_mac:
      name: TR2 (Mac)
      if: vars.MACOS_ENABLE == 'true'
      uses: ./.github/workflows/job_build_tr2_macos.yml
      with:
        target: debug
        let_mac_fail: true
      secrets: inherit
