name: Publish a new TR2X release

permissions:
  contents: write

on:
  push:
    branch: stable
    tags:
      - "tr2-*"

  workflow_dispatch:
    inputs:
      draft:
        description: "Draft"
        required: true
        type: boolean
        default: false
      prerelease:
        description: "Prerelease"
        required: true
        type: boolean
        default: false
      tag_name:
        description: "Tag name"
        required: false
        type: string
        default: github.ref_name

jobs:
  package_multiplatform:
    name: Build release assets
    if: vars.RELEASE_ENABLE == 'true'
    uses: ./.github/workflows/job_build_tr2.yml
    secrets: inherit

  publish_release:
    if: vars.RELEASE_ENABLE == 'true'
    name: Create a GitHub release
    needs:
      - package_multiplatform
    with:
      draft: ${{ inputs.draft || false }}
      prerelease: ${{ inputs.draft || false }}
      tag_name: ${{ inputs.tag_name || github.ref_name }}
      changelog_game_version: 2
    uses: ./.github/workflows/job_release.yml
